### ISSUE TITLE
Meta Issue: Address known cargo Audit issues

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#1024]
Currently, we have to ignore cargo audit issues. These are not critical fixes, but still should be addressed.

- [ ] RUSTSEC-2020-0041

**Comment by pjenvey** [comment]
There's an upgrade to `sized-chunks` resolving RUSTSEC-2020-0041 but we're stuck with it due to pinning ourselves to an older sentry (due to https://github.com/getsentry/sentry-rust/issues/277 ).

We might wanna try out the latest sentry to see if it's still an issue.

**Comment by jrconlin** [comment]
Yep, just cataloging that it's an issue. IIRC, later versions of sentry dropped support for `failure`, so we're blocked on https://github.com/mozilla-services/syncstorage-rs/issues/1017

**Comment by pjenvey** [comment]
Another potential option: can also [copy/paste the failure support code](https://github.com/getsentry/sentry-rust/issues/313#issuecomment-764674346) needed if we want to upgrade sentry before switching off failure.
