### ISSUE TITLE
Update code to use Futures 0.3+ / Tokio 1.3.0+

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#1025]
Futures 0.3 and Tokio 1.3.0 are significant updates. These will require significant changes to the code in order to be properly supported. Not updating to these libraries prevents some libraries from updating, potentially increasing risk.

**Comment by pjenvey** [comment]
The big blocker for this is actix-web, its 4.0 release will upgrade to futures 1.x. Currently in 4.0 beta4.

**Comment by ethowitz** [comment]
[JIRA](https://mozilla-hub.atlassian.net/browse/CONSVC-63)

**Comment by ethowitz** [comment]
[JIRA](https://mozilla-hub.atlassian.net/browse/CONSVC-63)

**Comment by pjenvey** [comment]
This was completed as part of the actix-web 4 upgrade https://github.com/mozilla-services/syncstorage-rs/issues/1249, closing
