### ISSUE TITLE
Tokenserver: Add node assignment logic

### ISSUE THREAD

**Issue by ethowitz** [mozilla-services/syncstorage-rs#1051]
We'll need to translate the node assignment logic from the old Tokenserver. Most of that logic lives in [this file](https://github.com/mozilla-services/tokenserver/blob/0fbf534dbe305f83f8cb43f8090c9dd4fde78805/tokenserver/assignment/sqlnode/sql.py). As part of this work, we'll need to handle changes to the `cilent_state` field in the request.

**Comment by jrconlin** [comment]
[Jira ticket](https://jira.mozilla.com/browse/CONSVC-160)

**Comment by jackyzy823** [comment]
Something for self-hosting:
1.  For self-hosting , old syncserver implement  use [staticnode assignment](https://github.com/mozilla-services/syncserver/blob/master/syncserver/staticnode.py) . which results different database structure of `users` . So either staticnode assignment or a db upgrade script needs to be implemented for self-hosting.

2. for self-hosting, old syncserver implement mounts tokenserver and server-syncstorage under two routes: `/token/` and `/storage/` , for `syncstorage-rs` should we implement this for self-hosting to avoid user change `identity.sync.tokenserver.uri` in `about:config`

**Comment by ethowitz** [comment]
Hey @jackyzy823, the work to make syncstorage-rs self-hostable will be done as part of a separate project. But to your points:
1. For simplicity's sake, I'm thinking it might make sense to use the same node assignment logic and database schema for self-hosting. Rather than add separate static node-assignment logic, we could just have a single node in the database to which users would always be assigned (in which case you’re right that we’d need to provide a script to migrate the database to the new format)
2. When we complete the work to make syncstorage-rs self-hostable, I expect we'll take an approach similar to the one we used for the old syncstorage. I agree that it would make sense to keep the configuration as consistent as possible so users don't have to do too much work to upgrade.
