### ISSUE TITLE
Add Tokenserver configuration info to README

### ISSUE THREAD

**Issue by ethowitz** [mozilla-services/syncstorage-rs#1082]
Let's add information about how to configure the Tokenserver functionality of the service. We should include info about:
- Which environment variables should be set (the Tokenserver database URL, RSA public key components, etc.)
- Where to point the `identity.sync.tokenserver.uri` pref in Firefox (`http://localhost:8000/token/1.0/sync/1.5`)
- How to set up the database

There will likely be more we want to add as the project develops. We should wait to do this until closer to the end of the project.

**Comment by jrconlin** [comment]
[Jira ticket](https://jira.mozilla.com/browse/CONSVC-162)
