### ISSUE TITLE
Tokenserver: Migrate any necessary scripts

### ISSUE THREAD

**Issue by ethowitz** [mozilla-services/syncstorage-rs#1086]
We'll need to migrate some of the scripts from [this](https://github.com/mozilla-services/tokenserver/tree/master/tokenserver/scripts) directory. Many of them may not be necessary anymore (depending on the outcome of #1085).

**Comment by jrconlin** [comment]
[Jira ticket](https://jira.mozilla.com/browse/CONSVC-163)
