### ISSUE TITLE
Tokenserver: Consume FxA account change webhooks

### ISSUE THREAD

**Issue by ethowitz** [mozilla-services/syncstorage-rs#1090]
On the legacy version of Tokenserver, [this script](https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/scripts/process_account_events.py) is run in a separate process to poll SQS for messages relating to password changes/resets (needed to update the `generation` number) and account deletions (needed so we can clean up old users). New functionality documented [here](https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa#webhook-events) allows us to subscribe to webhooks triggered by account events. This would make things much simpler, since we wouldn't need to stand up a separate process to poll for changes. Let's stand up an endpoint to listen to these webhooks. The format is defined [here](https://github.com/mozilla/fxa/tree/main/packages/fxa-event-broker#relying-party-event-format).

**Comment by jrconlin** [comment]
[Jira ticket](https://jira.mozilla.com/browse/CONSVC-164)

**Comment by ethowitz** [comment]
Unfortunately, the webhooks feature isn't architected in a way that can support Tokenserver. We need to keep polling SQS.
