### ISSUE TITLE
Tokenserver: Add new endpoint

### ISSUE THREAD

**Issue by ethowitz** [mozilla-services/syncstorage-rs#1092]
https://docs.google.com/document/d/1A6Vn95hj1MlwBtGP5c-oOt_TQZ5VAoR9FFxBrpzMwfM/edit?usp=sharing

**Comment by jrconlin** [comment]
Linked to https://jira.mozilla.com/browse/CONSVC-115

**Comment by pjenvey** [comment]
Not totally clear what this one was but seems to have been part of the completed Tokenserver rewrite effort, closing
