### ISSUE TITLE
Update to rust epoch 2018

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#118]
For [upgrading autopush-rs](https://github.com/mozilla-services/autopush-rs/pull/92) I did a:

- cargo fix --edition
- cargo fix --edition-idioms
- migrated off of extern crate declarations (when possible)

**Comment by jrconlin** [comment]
Appending fix to #126

**Comment by pjenvey** [comment]
Going to finish this now so I can merge it and #136 back into #126
