### ISSUE TITLE
Reduce the DEFAULT_BSO_TTL to something more reasonable

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#1187]
Currently we have the `DEFAULT_BSO_TTL` value set to `2_100_000_000` seconds, or 66.5 years. Prior sync clusters didn't last that long. We should set this value to be something more reasonable.

We will need to coordinate with the Sync front end team to determine a more reasonable retention date for this data. (Possibly 6 months or 15_770_000 seconds)

**Comment by pjenvey** [comment]
Closed per (superseded by) https://mozilla-hub.atlassian.net/browse/DISCO-1437
