### ISSUE TITLE
Add a purgettl command line tool

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#119]
We haven't ported the purgettl.py script from python to rust. It's ran continuously in deployments.

There's a slight possibility we could use the python version ([when and if it's implemented](https://github.com/mozilla-services/server-syncstorage/issues/100)) but:

- we'd need to ensure the python spanner schema matches ours exactly
- it requires a python style config file when ran which our rust code doesn't otherwise use

It may make sense (at the very least for the sake of convenience) to reimplement it in rust.

**Comment by jrconlin** [comment]
Silly question, could this be a REST call? The command line tool could just be ` curl` with an auth token or use a nginx origin filter or something.

Might make some of the secondary auth functions a bit easier.

**Comment by jrconlin** [comment]
based on discussion with ops, they feel they can run a cron script to address this later. They feel that keeping operational commands separate from the application is a more secure idea.

**Comment by jrconlin** [comment]
https://cloud.google.com/spanner/docs/use-cloud-functions#functions-calling-spanner-python

Looks like we could use something like: 
```
from google.cloud import spanner

instance_id = 'spanner-test'
database_id = 'sync_kid'

client = spanner.Client()


def spanner_read_data(request):
    instance = client.instance(instance_id)
    database = instance.database(database_id)

    query = 'DELETE FROM bso WHERE ttl < TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)'

    with database.snapshot() as snapshot:
        results = snapshot.execute_sql(query)
        outputs.append(results)

    return '\n'.join(outputs)
```

**Comment by pjenvey** [comment]
https://github.com/mozilla-services/server-syncstorage/issues/97

**Comment by jrconlin** [comment]
https://cloud.google.com/spanner/docs/dml-partitioned
