### ISSUE TITLE
Build docker images

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#122]
- Setup a Dockerfile according to Dockerflow guidelines to build a syncstorage-rs image
- Setup circleci to build it

See autopush-rs's or channelserver's Dockerfile and the [Dockerflow repo's](https://github.com/mozilla-services/Dockerflow) examples for good bases to start from.

**Comment by jrconlin** [comment]
Going to take this since I need a local docker image to build. actix brings in a lib that can't yet understand `openssl 1.1.1b` yet.
