### ISSUE TITLE
Update to actix-web 1.0

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#126]
Edit: switched out this issue to solely focus on upgrading actix-web 1.0

**Comment by fzzzy** [comment]
Running the above commands currently errors out at cargo update because of version conflicts with ring. I've seen this before. It requires choosing versions of all dependencies which depend on ring such that they all depend on the same version of ring. So, this will take some work to investigate a working combination of versions.

**Comment by jrconlin** [comment]
Looks like actix-web is working on 1.0.0 which updates a bunch of that. 

Unfortunately. looks like there are also a number of breaking changes.

**Comment by jrconlin** [comment]
So, most of the changes are reasonably easy to deal with in the code. Two are a lot less so.

Apparently actix dropped rolling your own middleware, and having a TestServer.

**Comment by pjenvey** [comment]
actix-web's migration to 1.0 doc:

https://github.com/actix/actix-web/blob/master/MIGRATION.md

describes many of the App's initialization call changes that affects us, e.g. App::with_state(T) -> App.new().data(T)

A couple examples of conversion of custom Middleware -> Transform trait here:

https://github.com/actix/examples/commit/14eed91fcd73aa65247e145ed394d86989a93ee3#diff-24d9e194249630e11f90021cf6cecafd

**Comment by pjenvey** [comment]
I'm postponing this upgrade for now. The upgrade of everything except middleware isn't too bad. We have a pretty extensive use of middleware that calls into our extractors (FromRequest) and the 1.0 upgrade really makes this nasty.

Here's some of the things required:

- [ ] minor API changes
- [ ] initialization/App setup changes
- [ ] handlers now return `impl Future` vs actix-web's FutureResponse

for the middleware:

- [ ] Requires switching from the 0.7 Middleware trait to a new, more lower level `Service` Trait + an associated `Transform`
- [ ] Separate `start`/`response` methods are converted to a single `call` method that, much more like a Python decorator
- [ ] The `Service::call` method calls into an inner service (a chain of Services). In some of our middleware this appears to require wrapping the inner service in a Rc<RefCell<S>>
- [ ] Using `HttpRequest` (and thus our associated extractors we heavily call in middlewares) is now discouraged from being used within `Service::call`. You *can* get an HttpRequest by consuming a `ServiceResponse`: but then you're unable to reconstruct a `ServerResponse`, which is the required arguments to the next `Service` call. Our `DbTransaction` and `PreConditionCheck` heavily call into extractors. Fixing this requires a big change in how this is done. We can't reconstruct the original `ServiceRequest` [because it's unsafe](https://github.com/actix/actix-web/issues?utf8=%E2%9C%93&q=is%3Aissue+ServiceRequest+from_parts). Nikolay is looking into alternatives (like maybe FromRequest can take a ServiceRequests?)

**Comment by fzzzy** [comment]
🎉🏆💯🎆
