### ISSUE TITLE
Add database crates

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/syncstorage-rs#1277]
Add the following crates (dependencies are noted as sub-bullets):

* syncstorage-db: Code that neatly combines and exposes the functionality of syncstorage-mysql and synsctorage-spanner for consumption by syncstorage-web
  * syncstorage-mysql: MySQL impls for the database traits in syncstorage-db-common
  * syncstorage-spanner: Spanner impls for the database traits in syncstorage-db-common
* tokenserver-db: Tokenserver database-related code
* syncstorage-mysql
* syncstorage-spanner

syncstorage-db and tokenserver-db should provide an easy-to-use high-level API exposing database functionality. This functionality will eventually be consumed by syncstorage-web and tokenserver-web.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-1940)

**Comment by ddurst** [comment]
Test comment in GH.

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Moved from CONSVC to SYNC as a test.

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Moved from SYNC back to CONSVC.
