### ISSUE TITLE
Investigate Client SDK Options (google-apis-rs)

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#128]
Let's take a look at adding async support to google-apis-rs. At the very least this gives us a path of using the sync version now with an option to migrate to async later.

This won't get us gRPC support in the near term but at this point let's not consider that a massive deal breaker vs unblocking implementation of Spanner support

**Comment by jrconlin** [comment]
Heh, the JWT is actually invalid, but the `jws` library doesn't flag it as so.
The header being presented is a properly signed "`null`.`null`._signature_"
awesome.

**Comment by fzzzy** [comment]
This work has been ongoing in this branch: https://github.com/fzzzy/google-apis-rs/tree/wip-update-to-hyper-0.12

The remaining work involves updating yup-oauth2 to return futures. We're going to close this investigate issue, and open new issues for the remaining work.
