### ISSUE TITLE
Use dependabot

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#131]
Once #126 is done we can turn on dependabot to keep deps up to date.

https://github.com/mozilla/application-services/issues/1105

**Comment by jrconlin** [comment]
hrm. Current `actix-web` 0.7.19 has a soft dependency on the older `actix` 0.7.9. Updating to `actix` 0.8.2 breaks the application. This critical is not exposed by current unit testing. We need to add some integration checks to ensure that any such critical is caught before dependencies are updated.

**Comment by tublitzed** [comment]
@jrconlin how does it break the application?

**Comment by jrconlin** [comment]
The problem was occurring when the application was running. On init, it would raise the error and the app would fail out. 

It might be worth seeing if newer version of actix-web still exhibit the error.

**Comment by fzzzy** [comment]
Turned this on for the syncstorage-rs repo.

**Comment by piegamesde** [comment]
Can we please configure dependabot to be less spammy? At the moment, ~75% of all open pull requests are by it, the other ones are getting drowned

**Comment by jrconlin** [comment]
Normally, I include "NOT dependabot" in the search 
e.g.
https://github.com/mozilla-services/syncstorage-rs/pulls?q=is%3Aopen+is%3Apr+NOT+dependabot+
