### ISSUE TITLE
No syncserver.ini file when cloning repo?

### ISSUE THREAD

**Issue by pickinanameainteasy** [mozilla-services/syncstorage-rs#1342]
According to the documentation, I need to make a few changes to my syncserver.ini file in order to connect to Firefox. (https://github.com/mozilla-services/syncstorage-rs#connecting-to-firefox). However this links to the old syncserver repo which is no longer maintained. Am I supposed to clone this out of date repo and make the changes there or do I clone this repo and edit a different .ini file?
Instructions unclear

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1820)

**Comment by neosheo** [comment]
Ok, where can I set the 'master_secret' for syncstorage-rs?

**Comment by pickinanameainteasy** [comment]
Ok great. But where can i set the 'master_secret' for syncstorage-rs?

**Comment by pickinanameainteasy** [comment]
Ok. Quick question. If i set this database up and connect it to a Firefox browser that I'm logged into my Firefox account on,  it will download all my bookmarks into the local database?

Let's say I'm signed into my Firefox account on another device,  if i save a new bookmark to my Firefox account can i have the local server sync with the Firefox account and therefore add the new bookmarks to the local database?

And finally can i connect a different browser (librewolf) to the local database and have it sync the bookmarks from the local database?

**Comment by sddsc90** [comment]
> And finally can i connect a different browser (librewolf) to the local database and have it sync the bookmarks from the local database?

Did you get this to work in any way?
I'd love to change to librewolf, and this would be a fantastic addition - I haven't tried to make it work anywhere yet.
