### ISSUE TITLE
Make docker images more podman friendly

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#1433]
(from [mb](https://github.com/mb) via https://github.com/mozilla-services/syncstorage-rs/pull/1431) 

> Make docker files more [podman](https://podman.io) friendly by specifying that images come from docker.io. It would be possible to specify the dependency as docker.io/mysql instead of docker.io/library/mysql. The [doc seems to prefer](https://podman.io/getting-started/#searching-pulling--listing-images) the longer version.

e.g. 
```diff
- FROM rust:1.64-buster as builder
+ FROM docker.io/library/rust:1.64-buster as builder
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2078)

**Comment by pjenvey** [comment]
Resolved in https://github.com/mozilla-services/syncstorage-rs/pull/1479 & https://github.com/mozilla-services/syncstorage-rs/pull/1492
