### ISSUE TITLE
DEBG calculated mac doesn't match header

### ISSUE THREAD

**Issue by bb5d0** [mozilla-services/syncstorage-rs#1440]
I have a working apache reverse proxy like this
```
<Location />
   ProxyPass http://127.0.0.1:8000
   ProxyPassReverse http://127.0.0.1:8000
</Location>
```
but when I change the location-URI to `<Location /abc>` I get a the server message 

> DEBG calculated mac doesn't match header

in the browser sync-log I get the message 

> Sync.ErrorHandler	ERROR	Sync encountered a login error

but all URLs look fine and **https://domain/abc/__heartbeat__** is working!
the same also for `<Location /abc/>`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-2106)

**Comment by ethowitz** [comment]
Hmm, I am guessing this is related to #1217.

In short, your browser is generating a MAC header using the `domain/abc` path, but when your reverse proxy forwards the request to the server, it strips the `/abc` from the path, and the server is attempting to verify the MAC using the version of the path without the `/abc`. I'm going to close this issue in favor of #1217, but I will post an update there now.
