### ISSUE TITLE
How to use other mysql server not localhost

### ISSUE THREAD

**Issue by bluestar800** [mozilla-services/syncstorage-rs#1498]
When I searched for this project, I was very excited and thanked the developers for their contributions.

I have a mysql server already in use on my network, and I can create a dedicated account and database for mozilla.

I read everything in the readme and tried to "make run_mysql". I modified the local.toml file to point the mysql address to the mysql server's IP address and dedicated account (not localhost),

When I try to make, it show me that  can't connect to mysql . I checked the display information  find mysql address was changed to "localhost"  instead of the mysql server address when making.

I want to ask, 
1  Is there support for other mysql server not localhost ? And what should I do ?
2 Can I directly use containers already built in docker hub? And What parameters are supported?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3992)

**Comment by jackyzy823** [comment]
>  I modified the local.toml file to point the mysql address to the mysql server's IP address and dedicated account (not localhost),

Do you sure  that you have mde a copy of `config/local.example.toml` to `config/local.toml` and then edited `config/local.toml`? (Or maybe you just edited config/local.example.toml" )

> 2 Can I directly use containers already built in docker hub? And What parameters are supported?
Newest version no . See https://github.com/mozilla-services/syncstorage-rs/issues/1495

Basically all settings could be passed from env. For reference: https://github.com/mozilla-services/syncstorage-rs/blob/master/docker-compose.e2e.mysql.yaml#L25-L43

**Comment by bluestar800** [comment]
> > I modified the local.toml file to point the mysql address to the mysql server's IP address and dedicated account (not localhost),
> 
> Do you sure that you have mde a copy of `config/local.example.toml` to `config/local.toml` and then edited `config/local.toml`? (Or maybe you just edited config/local.example.toml" )
> 
> > 2 Can I directly use containers already built in docker hub? And What parameters are supported?
> > Newest version no . See #1495
> 
> Basically all settings could be passed from env. For reference: https://github.com/mozilla-services/syncstorage-rs/blob/master/docker-compose.e2e.mysql.yaml#L25-L43

Thank you for reminding me, although I do the same, but thank you.
I tried many times. In the end，I using containers that is in docker hub by pass some env , which worked well. mysql server ip is other machine
