### ISSUE TITLE
tokenserver requires deprecated boto

### ISSUE THREAD

**Issue by 0-wiz-0** [mozilla-services/syncstorage-rs#1532]
https://github.com/mozilla-services/syncstorage-rs/blob/143e93b66f27e0d03509d17db8da53f9397fe73e/tools/tokenserver/requirements.txt#L1 says that tokenserver needs boto.
boto has a big warning on its [homepage](https://github.com/boto/boto/) that it has been replaced by boto3 and is unsupported.
(I can't tell from the README if tokenserver itself is still supported or needed.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4210)

**Comment by jrconlin** [comment]
Yeah, [the script](https://github.com/mozilla-services/syncstorage-rs/blob/master/tools/tokenserver/process_account_events.py) that relies on that is also fairly old. 

I contacted the FxA folk, and they suggest using a WebHook based system. If you don't mind, I may close this issue and open up a new one proposing we add the webhook to the syncstorage-rs tokenserver implementation.

**Comment by 0-wiz-0** [comment]
Sure, let's do it this way! Thanks for the quick reply.

**Comment by data-sync-user** [comment]
> **Barry Chen** commented from Jira:

The patch for [https://mozilla-hub.atlassian.net/browse/STOR-549](https://mozilla-hub.atlassian.net/browse/STOR-549|smart-link) includes this upgrade so I’m assigning this issue to myself.
