### ISSUE TITLE
Adapt mysql tests to the generic Db trait

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#156]
The db mod test suite currently targets the mysql specific interface. However it's really a test of the Db trait interface itself, minus a few places where it dips down into internal methods.

The tests should run against the Db trait instead: that way they can test against Spanner's trait impl. as well as mysql's.

Any places where it needs unexposed internals can be exposed to the tests only (like e.g. the with_delta method that already works this way)

**Comment by fzzzy** [comment]
There are some other generic parts that are currently in the mysql module, we should move those out too. Should we open new issues for them, though?

`macro_rules! mock_db_method` should be somewhere generic.

`CollectionCache` should be somewhere generic.

**Comment by pjenvey** [comment]
The mock_db_method usages outside of the module are temporary, so we might as well leave it in mock.rs

Logged  #158 for CollectionCache. I imagine there will be other mysql parts we'll want to rearrange too
