### ISSUE TITLE
Setup Spanner transactions (lock_for_read/write)

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#157]
Once we implement a spanner `DbPool` and a basic `Db` impl, the next step (before building out API calls) is to implement `lock_for_read/write`. These will setup the appropriate Spanner transaction.

The Python version's impls (spanner):
https://github.com/mozilla-services/server-syncstorage/blob/fee296f/syncstorage/storage/spanner.py#L179

- lock_for_read should setup a read transaction. By default this is a strong read in spanner, so that's all that's needed (vs other db backends that [e.g. acquire a lock](https://github.com/mozilla-services/server-syncstorage/blob/fee296f32867bba7b9bb85a31942e0f12d01b77a/syncstorage/storage/sql/__init__.py#L196))
- lock_for_write sets up a r/w transaction, grabs the users's last_modified time and current timestamp from the db, then ensures the timestamps have a large enough delta. Otherwise it triggers a ConflictError (503)

**Comment by fzzzy** [comment]
This is now implemented in the spanner-pool branch. While it is not yet merged, I am going to close this and continue work on https://github.com/mozilla-services/syncstorage-rs/issues/169
