### ISSUE TITLE
Bump python libs per security alerts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/syncstorage-rs#1573]
Dependabot has been nagging us about a number of security alerts in our older cryography/pyramid versions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4301)

**Comment by jrconlin** [comment]
Yeah, kinda planning on updating those on the next dependency update run, but if y'all want to do them earlier, 👍🏻

**Comment by pjenvey** [comment]
I'm admittedly doing the bare minimum here just as a quickie to get rid of the dependabot alerts
