### ISSUE TITLE
Adapt mysql batch tests to the generic Db trait

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#160]
Followup to #156:

I won't tackle the batch tests in #156 because they live in a separate file. Though they need to be moved/adapted over as well.

**Comment by pjenvey** [comment]
We should also cleanup the duplicated helpers when moving these and consider [small improvements](https://github.com/mozilla-services/syncstorage-rs/pull/161#discussion_r299232868) to the helpers as well

**Comment by jrconlin** [comment]
@pjenvey Was this addressed by #199?
