### ISSUE TITLE
Sync server stopped working on firefox for android. 

### ISSUE THREAD

**Issue by awptechnologies** [mozilla-services/syncstorage-rs#1610]
I have 4 devices that use the sync server. All of my desktops/laptops sync fine. History extensions and tabs.  My phone stopped all of a sudden. I updated to latest Firefox version and it is still not syncing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4439)

**Comment by jrconlin** [comment]
Is this related to you trying to connect to your own instance of syncstorage or are you experiencing a problem with your mobile sync (using all the standard stuff)?

For "stock" sync, you may need to log out of sync on your mobile device, and then log back in. If that doesn't work you might want to ask in the [#sync channel on chat.mozilla.org](https://chat.mozilla.org/#/room/#sync:mozilla.org). 

For your own server, you'll need to [enable dev mode](https://github.com/mozilla-services/syncstorage-rs/wiki/Enabling-Dev-Mode-on-Android) on your mobile device and then set the "custom sync server" to the appropriate URL.

**Comment by awptechnologies** [comment]
I use my own server. It all of a sudden started working. I had already enabled dev mode and set url.
