### ISSUE TITLE
Remove the smallvec dependency

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#166]
We're temporarily hardcoding it in Cargo.toml to workaround RUSTSEC-2019-0009 (but don't actually depend on it), it should be removed at some point

**Comment by jrconlin** [comment]
The dependency is in actix. Moving to >1.0 should resolve this. 

See PR https://github.com/mozilla-services/syncstorage-rs/pull/159/files#diff-80398c5faae3c069e4e6aa2ed11b28c0
