### ISSUE TITLE
Improve and standardize trace statements and logging

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#174]
The app currently does not provide sufficient debugging statements or clarity around some error types. These are messages that do not need to be propagated to production logs, but are immensely valuable during debugging and diagnostics.

**Comment by fzzzy** [comment]
According to https://github.com/mozilla-services/websec-check/blob/master/rust.md we should use `slog-mozlog-json` for logging.

**Comment by pjenvey** [comment]
A good place to start here is adding trace statements. As an example, in the autopush-rs codebase, we've added trace logs indicating entry to important method calls: https://github.com/mozilla-services/autopush-rs/blob/1086de7/autopush/src/client.rs#L321

There's also many dbg! statements lying around in our codebase, added during development. Many of these could be cleaned up and or converted to log trace methods.

We use slog for its structured logging capabilities, so we'd want to use its trace! macro.

**Comment by jrconlin** [comment]
I'm guessing you mean `debug!` here instead of `dbg!`.
I've only found one [`dbg!`](https://github.com/mozilla-services/syncstorage-rs/search?q=dbg!), and it's in `server/test.rs` There are a few in the google-apis, but I don't think that we should be responsible for cleaning those up.
