### ISSUE TITLE
Switch to execute_streaming_sql

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#205]
Spanner provides a streaming sql request call, which should act more resource efficient for large result sets. 

The Python client lib (and likely other libs) default its sql calls to using this API. It uses the same `ExecuteSqlRequest` struct for building the request, but returns a `PartialResultSet` vs a regular `ResultSet`.

The result iterator would have to adapt to this different ResultSet.

grpcio provides a `ClientSStreamReceiver` for handling the stream. It supports an async interface. There's also a `wait` call for a sync request? Would we need to defer this to a thread pool to take advantage of it before we go full async?

**Comment by jrconlin** [comment]
Gauging as 8 because I suspect that this may require multi-week effort (async and testing)

**Comment by pjenvey** [comment]
Apparently the non streaming API has a limit of 10mb result sets:

https://sentry.prod.mozaws.net/operations/syncstorage-stage/issues/6625661/?query=is:unresolved

```
A database error occurred: RpcFailure(RpcStatus { status: RpcStatusCode(9), details: Some("Result set too large. Result sets larger than 10.00M can only be yielded through the streaming API.") })
```

-> p1
