### ISSUE TITLE
Cleanup google-apis-rs support

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#211]
When we're ready to switch over to the new client SDK fully, we should eventually remove support for google-apis-rs.

First let's just cleanup a few of the workarounds it google-apis-rs required:

e.g. 

- [ ] the sql COALESCE calls to workaround its buggy null handling
- [ ] the similar 'ts0' workaround in `get_storage_timestamp_sync`

**Comment by pjenvey** [comment]
I don't think we actually have to fully remove this code yet.

google-apis-rs support brought some dependency conflicts with the hawk crate. Those seem to be resolved by commenting out the hyper/hyper-rusttls dependencies in Cargo.toml.

So we can limit this issue to simply removing the couple of google-apis-rs workarounds

**Comment by jrconlin** [comment]
Merged via https://github.com/mozilla-services/syncstorage-rs/pull/240
