### ISSUE TITLE
Cleanup TODOs in spanner backend

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#212]
We have a number of TODOs piling up (see the TODO and XXX comments) in the spanner backend.

These should all be revisited/fixed/cleaned up.

**Comment by tublitzed** [comment]
@pjenvey would you consider all the TODOs/XXX items to be p1 here, or just a subset of them?

**Comment by pjenvey** [comment]
> @pjenvey would you consider all the TODOs/XXX items to be p1 here, or just a subset of them?

Likely a subset. I'll log separate issues for non p1s (and maybe even p1s) that shake out of this one
