### ISSUE TITLE
Find a way to differentiate between old sync/new sync for tracking purposes.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#222]
We'll need to find a way to make sure we can bucket our tracking data for old vs. new Sync as we start to roll this out.

Not an absolute blocker for shipping, but it would be great to get this in very soon afterwards.

**Comment by jrconlin** [comment]
Thinking about this a bit more:
1) What do we mean by "new" vs. "old" (e.g. would source machine be enough to differentiate?)
2) How do we want to track and dashboard this difference? (Presuming via metrics and tags, but good to make sure)
3) Are there other tags we need to track (e.g. collection_id, size, etc.)

We have some [very basic metricking](https://github.com/mozilla-services/syncstorage-rs/pull/200) in place, but it needs to be expanded to meet expected monitoring.

**Comment by fzzzy** [comment]
I think knowing which machine would be enough.

**Comment by tublitzed** [comment]
@jrconlin:

1. By "old" vs "new", what I mean is customers using existing Sync vs Spanner backed Durable Sync. The reasoning for this is so that as we start rolling this out, we can be actively tracking any differences in existing metrics.
2. I've found these existing Sync dashboards: [https://sql.telemetry.mozilla.org/dashboard/sync-leif-status-dashboard-wip](Telemetry, via Leif), [https://app.datadoghq.com/dashboard/pu6-y3x-vj9/sync-15?from_ts=1568979305080&live=true&tile_size=m&to_ts=1568982905080](Datadog). If there are more, let me know. I'll also check with Alex D. on this one.

My plan is determine which top level metrics we most care about, and then re-create one/both of these dashboards with old vs new sync versions tracked side by side.
3. Not that I know of yet, but if so, I'd think that would be a separate issue entirely. Ie, the goal here is just to differentiate new vs old for existing metrics.

**Comment by jrconlin** [comment]
cadence allows `Counter.incr_with_tags()` which allows additional tag values to be passed to the metric server (e.g.
```
client
    .incr_with_tags("sync.request.get_collections")
    .with_tag("version", env!("CARGO_PKG_VERSION"))
```

Would something like that suffice? In which case we could just add it to the bottleneck `incr()` method in `metrics::Metrics::incr()`

**Comment by pjenvey** [comment]
@jrconlin does syncstorage-rs's metrics (individual metric names) match the python exactly?

The current python cluster's metrics go over to datadog, syncstorage-rs's metrics will end up in influx (grafana). So I suspect differentiating our server metrics should be pretty straightforward (they'll live in different dashboards).

As for distinguishing client's telemetry, there's an issue tracking it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1582317

**Comment by jrconlin** [comment]
@pjenvey short answer: heck no. 
longer answer: I'm unfamiliar with the various decorator and secondary effect based metricking calls used by `[mozsvc.metrics](https://github.com/mozilla-services/mozservices/blob/master/mozsvc/metrics.py)` A fair number of the metrics I've spotted doing a casual inspection of the python code are timer based, so I should probably add that as well.
