### ISSUE TITLE
SpannerDb::timestamp should return CURRENT_TIMESTAMP()

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#223]
SpannerDb inherited MysqlDb's behavior where it creates its self.timestamp() value from the current server's time.

For the sake of sanity we should be using `CURRENT_TIMESTAMP()` from Spanner itself instead (as the python does)

**Comment by jrconlin** [comment]
I noticed that `self.timestamp` and `CURRENT_TIMESTAMP()` often return radically different times. (I'm 100% onboard with using the db's `CURRENT_TIMESTAMP()` for any modification times, but wonder how that will play with clients.

**Comment by pjenvey** [comment]
> I noticed that `self.timestamp` and `CURRENT_TIMESTAMP()` often return radically different times.

They're both UTC. Assuming an accurate clock, they should be similar (they look the same minus a few nanos over here)
