### ISSUE TITLE
`collection` table IDs below 100 need to be reserved for system use.

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#231]
See [bug 1364005](https://bugzilla.mozilla.org/show_bug.cgi?id=1364005) The collections table reserves ids < 100 for system use. We need to ensure that any new collections occur after id 100. <insert JR grumbling about name collisions and system flags or at least prefixes because, really... >

**Comment by fzzzy** [comment]
This was fixed by https://github.com/mozilla-services/syncstorage-rs/commit/46c650a1794881e58cf1af5abdefadbea9b72aec
