### ISSUE TITLE
Tracking issue for getting Durable Sync up on staging

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#250]
The bugzilla issue lives [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1586910) for ops to deploy. Once that's done, we can start poking around and see what else (if anything) needs to be done here.

After we're verified up in stg, @tublitzed to notify QA and Security that we're ready for testing/reviews.

**Comment by jrconlin** [comment]
cadence allows `Counter.incr_with_tags()` which allows additional tag values to be passed to the metric server (e.g.
```
client
    .incr_with_tags("sync.request.get_collections")
    .with_tag("version", env!("CARGO_PKG_VERSION"))
```

Would something like that suffice? In which case we could just add it to the bottleneck `incr()` method in `metrics::Metrics::incr()`

**Comment by tublitzed** [comment]
Issue was found with existing release, new [issue here](https://bugzilla.mozilla.org/show_bug.cgi?id=1588406) tracking request for deploying latest version.
