### ISSUE TITLE
Cleanup default config settings.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#253]
With [this change](https://github.com/mehcode/config-rs/issues/60) to config-rs, a bug has been fixed that was preventing us from using the `Default` implementation for the `Settings` struct. We can remove most or all of the calls to `set_default` in `Settings::with_env_and_config_file` in favor of the defaults set in the `Default` implementation.

**Comment by pjenvey** [comment]
This is a pretty easy cleanup to accomplish, by:

-  adding `#[serde(default)]` to `Settings`, which makes the `Default` impl be utilized which lets us..
-  kill the many `set_default` calls that duplicate those defaults in `Settings::with_env_and_config_file`
-  additionally, when removing the `set_default` calls, spot check their values -- ensure the `Default` implementation's values match those (just in case any have gotten out of sync over time)

As an example see how [this was done for contile ](https://github.com/mozilla-services/contile/commit/71b9df3a3eb4b2)

**Comment by ethowitz** [comment]
[JIRA](https://mozilla-hub.atlassian.net/browse/CONSVC-1700)

**Comment by ethowitz** [comment]
This will be completed as part of the crate reorganization work
