### ISSUE TITLE
doc: Add system dependencies to README

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#255]
@fzzzy noted a few missing libraries when trying to compile locally. Creating issue here to track them, and to later update README with the system dependency lists.

these include:
libssl-dev
libmysql-dev

**Comment by fzzzy** [comment]
Specifically, on ubuntu lts in a virtualbox vm.

**Comment by jrconlin** [comment]
fair point, but if we need users to pre-install libraries, we should at least list them. 

For Autopush we had a Makefile to wrap some of that. I think listing them is probably good enough here.

**Comment by tublitzed** [comment]
I had to install `cmake` just now on OSX when running locally.

**Comment by pjenvey** [comment]
The Dockerfile's a good reference for what's needed (it includes everything we've listed so far).

**Comment by svensevenslow** [comment]
Hi! I'm an Outreachy 2020 participant, I'd like to work on this issue, please assign it to me

**Comment by svensevenslow** [comment]
Hi! Sorry for the inconvenience. I won't be working on this issue, someone else can work on it.

**Comment by amrita72** [comment]
Hi! @jrconlin. I think I can track all the deps and list them in the README. I'll be using [`ubuntu docker image`](https://hub.docker.com/_/ubuntu) for that.

**Comment by jrconlin** [comment]
Updating the README and possibly the dockerfile is always useful. Things change, fairly frequently, so there may be needed changes.

**Comment by amrita72** [comment]
@jrconlin, Following packages are required to **build** syncstorage-rs on `Ubuntu 18.04`.

- rust
- make
- cmake
- gcc
- pkg-config
- golang
- libmysqlclient-dev
- libssl-dev
- libcurl4-openssl-dev
