### ISSUE TITLE
Populate staging with spanner data

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#258]
We need to find a way to migrate existing data in staging over to staging version of spanner.

**Comment by jrconlin** [comment]
I'm not really sure we can migrate things over.

Spanner imposes a few restrictions on columns and is not quite real SQL. Commands like `ALTER TABLE...` only allow you to add or drop columns (which would drop the data we're trying to migrate). Likewise, "key" columns cannot be edited once the table is created.

It might be possible to export the old data, create the new schema and then import the data into that altered schema using something like Dataflow. If it's 300GB, it's going to take a bit. It might be worth just updating the existing test loaders.

**Comment by fzzzy** [comment]
I think we should just say that we can't do this, and start loading the new db with data.

**Comment by tublitzed** [comment]
Re-opened and re-scoping this one a bit; if we can't migrate then we at least should find a way to populate the stg DB so we can test against it.

**Comment by jrconlin** [comment]
DUP of https://github.com/mozilla-services/syncstorage-rs/issues/284

**Comment by jrconlin** [comment]
![image](https://user-images.githubusercontent.com/35755/67445361-80ce2e80-f5c1-11e9-8550-c0d20f0a7397.png)
