### ISSUE TITLE
Fix failing db-tests for OSX (or document workaround for now)

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#259]
to repro, on osx: `cd db-tests && cargo test`

We may need to just add instructions for the hacky fix (ie, compile locally set to a specific grpcio verison) and then also file a bug against that project for the time being.

**Comment by fzzzy** [comment]
Here is a patch which will temporarily work around the breakage until this is fixed for real.

```
diff --git a/db-tests/rust-toolchain b/db-tests/rust-toolchain
index c8d3401e6e..1334c94aff 100644
--- a/db-tests/rust-toolchain
+++ b/db-tests/rust-toolchain
@@ -1 +1 @@
-beta-2019-10-03
+nightly-2019-06-27
diff --git a/db-tests/src/lib.rs b/db-tests/src/lib.rs
index b5a1cc7268..054087ac69 100644
--- a/db-tests/src/lib.rs
+++ b/db-tests/src/lib.rs
@@ -1,3 +1,5 @@
+#![feature(await_macro, async_await)]
+
 #[cfg(test)]
 #[macro_use]
 mod support;
```

**Comment by fzzzy** [comment]
This is now fixed by one of the dependencies being updated. We're not sure exactly which. If you still have problems compiling, try:

```
rustup default stable
rustup update
rm Cargo.lock
cargo clean
cd db-tests
rm Cargo.lock
cargo clean
cargo test
```
