### ISSUE TITLE
accept header checks are too strict

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#264]
The extractors module compares the `Accept` header's value against supported content types. The value may potentially include weighting parameters (e.g. "application/json;q=0.9,/;q=0.2") which aren't parsed out, potentially breaking our comparison.

Python's webob `Request.content_type` field parses them out for us, maybe something in actix-web or elsewhere can do the same for us.

We see this on stage with some `DELETE` requests returning 406 Not Accepted responses

**Comment by jrconlin** [comment]
Be advised that actix_web uses `mime::Mime` to parse some headers like `Content-Type`, and it will reject invalid characters (such as `,` or `/`)
