### ISSUE TITLE
Manual testing against staging - Desktop

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#270]
In prep for the initial prod release, let's start doing some manual testing against staging this week. 

1. First, make sure you're connected to staging on each of your devices [following these instructions](https://docs.google.com/document/d/1KnFdE1ee-yv8En5QaPoRj3x2s9kTESoW0lGNh2LwIrI/edit). 

2. Then follow the steps [outlined here](https://docs.google.com/document/d/1fS-t_BoN33sfGRemN20IvY0i_JUvrlBdoEJP-qLEMJ4/edit#) paying specific attention to anything involving sync storage. Note: it may not be possible to test against staging with a mobile device at the moment. If needed, use two desktops.

3. Add any issues/oddities/notes you find to [this doc](https://docs.google.com/spreadsheets/d/1DoElh_8qEr9IdQCobRJktjJVYoU1plD3QQjIZTllFlQ/edit?usp=sharing) and we'll bug the ones that are confirmed.

If you're not sure if something you found is actually an issue, feel free to just use comments in this case as a jumping off point for discussion/triage.

**Comment by tublitzed** [comment]
Note: this is going to be blocked by the 0.1.2 release to staging - bugz issue lives [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1588406).

**Comment by jrconlin** [comment]
I assume by "two desktops" you mean to profile instances of firefox? (e.g. use the "-p --no-remote" options)

**Comment by tublitzed** [comment]
I mean "two machines". Considering that profiles and profile switching is a fairly advanced use of FF, it might not be a bad idea to test as we expect people to use this. AFAIK, users aren't generally sync-ing between profile instances.

**Comment by tublitzed** [comment]
I filed a secondary task for next week to test against [mobile devices](https://github.com/mozilla-services/syncstorage-rs/issues/271). So, assuming two machines, it might be easiest to use desktop since it's not possible to point iOS at staging, and I have yet to learn the trick to do it for Android (that being said, if you know it for Android, go for it). No reason this needs to be client specific, I just mentioned two desktops b/c I think that's simplest right now.
