### ISSUE TITLE
Test lockwise against stage (iOS)

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#272]
Since the point of durable sync is to better support lockwise, we should test lockwise against it before release.

**Comment by fzzzy** [comment]
@jrconlin tested this a bit and it seems to be working, but let's keep this bug open until someone tests the mac client.

**Comment by fzzzy** [comment]
I tried to test the iOS client, but then I realized I don't know how to change the tokenserver url, if it is even possible.

**Comment by fzzzy** [comment]
In the meeting yesterday, we discussed testing lockwise and fenix against stage instead of production by compiling our own builds with the stage url swapped in. So, I'm going to use that approach to test lockwise now.

**Comment by jrconlin** [comment]
Taking over Lockwise testing on Fenix and Android, since I'm the token Android user on the team.

**Comment by fzzzy** [comment]
We weren't able to test lockwise against stage, but we were able to test it against a spanner instance running on prod that only test accounts got assigned to.

It's working fine now.
