### ISSUE TITLE
Test Firefox iOS against stage

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#274]
This seems like a lower priority, but if we have time, we should see if Firefox iOS can sync with stage.

**Comment by tublitzed** [comment]
this may or may not be possible. See [this issue](https://github.com/mozilla-mobile/firefox-ios/issues/3150) for details. TL;DR - there's no way to set a custom token server in iOS. 

We should verify that this is still the cause though, since there's a long thread about workarounds [here](https://github.com/mozilla-mobile/firefox-ios/issues/5006).

**Comment by fzzzy** [comment]
It looks like it is possible if you set up the full fxa stack: https://github.com/mozilla-mobile/firefox-ios/issues/5006#issuecomment-501767382

**Comment by fzzzy** [comment]
Actually, further down in the thread, there is a person who was successful even without a full stack, and they wrote a useful looking blog post about it: https://daniel-ziegler.com/computer/netzwerk/linux/2019/07/07/Firefox-Sync-iOS/

**Comment by fzzzy** [comment]
It is able to connect to sync, and sync bookmark folders, but when it tries to sync the individual bookmarks it crashes. Then, every time you start it up after that, it tries to sync and crashes.

**Comment by BobWs** [comment]
> Actually, further down in the thread, there is a person who was successful even without a full stack, and they wrote a useful looking blog post about it: https://daniel-ziegler.com/computer/netzwerk/linux/2019/07/07/Firefox-Sync-iOS/

I followed the steps as he described but didn’t have success to sync my bookmarks. In the log I see that iOS connect to the server but that’s all, nothing happens no sync. Running syncserver in docker  on a Synology NAS.

**Comment by fzzzy** [comment]
Let's hold off on testing this further until Bob switches the ingress server to nginx.

**Comment by Section1977** [comment]
can confirm the issue
please fix
