### ISSUE TITLE
Write sql to get stg populated with data

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#284]

**Comment by fzzzy** [comment]
I believe we use the load tester to do this, with an environment variable to tell it not to delete.

**Comment by pjenvey** [comment]
> I believe we use the load tester to do this, with an environment variable to tell it not to delete.

We're going to try implementing a more direct method of populating junk data, which should hopefully load faster than the load test would

**Comment by jrconlin** [comment]
Tied to bug https://bugzilla.mozilla.org/show_bug.cgi?id=1589484

**Comment by jrconlin** [comment]
![image](https://user-images.githubusercontent.com/35755/67507058-0f36c480-f643-11e9-89e6-0e85199ee7e0.png)

A few notes: 
* Ballast stuffing took about 4 hours (the CPUs for the EC2 and Spanner were NOT happy).
* I will probably release another tools patch that includes a few tweaks to the tool set.
* The original script stuffed a lot of records under a small set of keys. Next tool update will generate more fake users to keep the keys a bit cooler. We can still easily spot and remove ballast later if need be.
* Ops will keep the stage box in place for little longer, mostly to deal with potential ballast reloading.
