### ISSUE TITLE
Reduce max_total records per Spanner's mutation per commit limit

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#298]
We currently advertise a `max_total_records` (Maximum BSO count across a batch upload) value of 10000 (matching the python version).

This exceeds Spanner's limit on mutations per transaction. Every column and index touched on a write counts toward a mutation. From playing around w/ the [write_batch tool](https://github.com/mozilla-services/syncstorage-rs/blob/c085ff8/tools/spanner/write_batch.py#L51), we seem to peak at about 2000 bsos before hitting [Spanner's 20k mutation limit](https://cloud.google.com/spanner/quotas#limits_for_creating_reading_updating_and_deleting_data).

(Probably due to bso's 8 columns plus a couple more for its associated secondary indicies = 10 mutations per write).

The load tester currently exceeds this limit:

https://sentry.prod.mozaws.net/operations/syncstorage-stage/issues/6493445/?environment=debug

(Nor does it currently respect the `/info/configuration`'s advertised limit: [syncstorage-loadtest#19](https://github.com/mozilla-services/syncstorage-loadtest/issues/19))

**Comment by pjenvey** [comment]
This lower value is not ideal for the client side, particularly e.g. a device's first sync where the device has a large number of bookmarks (>= 2k).

In that case the client must split the upload into smaller batches, increasing potential for the client getting into a race with another device also writing to storage.

Losing the race might result in the client/storage coming into an inconsistent state.

**Comment by pjenvey** [comment]
This is hopefully a temporary limit, see #299

**Comment by jrconlin** [comment]
It looks like this can be handled via a configuration option `limits.max_total_records`. I'm not sure how or if this can be expressed as an env, but it could be stored in a configuration file and called via the CLI as `--config spanner_config.ini` or something.
