### ISSUE TITLE
Batch impl improvements

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#299]
There's some tweaks to our batch implementation that could improve its performance:

- [x] When committing a batch, Instead of a round tripping the bsos (loading them from the batch table into syncstorage-rs, then writing them back to the bso table, both w/ accompanying json serialization/deserialization) we can offload this work to the db itself. 
  - The Python version does this (e.g.: https://github.com/mozilla-services/server-syncstorage/blob/a0f8117/syncstorage/storage/sql/queries_generic.py#L154 ). 
  - This seems especially feasible for inserts of new bsos see `APPLY_BATCH_INSERT` above
  - Updates will require a less efficient query (see `APPLY_BATCH_UPDATE` in the same file, a subselect for each row). We'll consider using it depending on what spanner's query plan thinks of it

- [x] With the db handling this, batch tables should really interleave w/ user_collections, ensuring user's batch data lives within the same Spanner split as their bso table (and thus a shorter network roundtrip when applying the batch)

- [x] Interleaving of batch tables requires a parent row entry in user_collections before a batch can be created, likely some kind of "tombstone like" row (say a timestamp of 0 which other queries would ignore)

- [ ] Further benefit from this change is it should allow higher batch max_total_records limits, depending on how updates are handled: https://github.com/mozilla-services/syncstorage-rs/issues/298#issuecomment-545184151 (with the feedback from the client team noting that reduced limits can cause some client nastyness, the slower Update w/ subselects may be necessary, at least some of the time)

Marking as p2 but would like to do this sooner rather than later, per it requiring a schema change

**Comment by rfk** [comment]
> a subselect for each row

I have a vague recollection that MySQL is smart enough to turn this subselect into some sort of join rather than executing it for each row; YMMV of course.

**Comment by pjenvey** [comment]
Query plans for the current changes in feat/299:

Given a user with:
- 6000 rows in bsos
- 2924 total rows in batch_bsos
  - 924 of which are existing bsos
  - 2000 of which are new bsos

Query plan for the batch_commit_update.sql:

<img width="1068" alt="Screen Shot 2019-11-01 at 2 31 30 PM" src="https://user-images.githubusercontent.com/14639/68057937-b7d4cc00-fcb4-11e9-9a20-f91dc8842937.png">

Query plan for the batch_commit_insert.sql:

<img width="955" alt="Screen Shot 2019-11-01 at 2 32 03 PM" src="https://user-images.githubusercontent.com/14639/68057949-befbda00-fcb4-11e9-9de0-804c61c258ef.png">

As expected the UPDATE is not great, every sub select (per each each row and column) is a separate execution.

The bad news is (as @fzzzy suggested) this change doesn't help w/ the mutation limit. We're  stuck w/ max_total_records (batch size) of 2000 #298 unless there's some other alternative.

Maybe the server could special case making > 1 transactions for committing a larger batch, but any of those transactions might fail, ending up w/ partially committed, bad state, not unlike the client issue.
