### ISSUE TITLE
Audit max_total_bytes per Spanner's mutation per commit limit

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#320]
Followup to #298:

I haven't double checked our max_total_bytes value, but Spanner has a 100mb commit size along w/ its 20k mutation limit.

Let's double check our value is under this limit for spanner

**Comment by jrconlin** [comment]
Cool. Hopefully the config file approach will also help reduce code impacts. IIRC, there's a Dockerfile / docker-compose option to specify a config file externally to the image, but that might be more for swarm approaches.

**Comment by pjenvey** [comment]
Apparently the config crate supports nested values via a `Environment::separator`: a suggested separator of `"__"` would allow `SYNC_LIMITS__MAX_POST_BYTES` (plain `_` clashes w/ its prefix handling), but it isn't very readable.

https://github.com/mehcode/config-rs/issues/104

Config file works for now (if ops ever needs to change these from their side we can consider alternatives)
