### ISSUE TITLE
Upgrade Rust version to 1.39

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#322]
In prep for transitioning over to use [async-await](https://blog.rust-lang.org/2019/09/30/Async-await-hits-beta.html).

**Comment by jrconlin** [comment]
Preliminary testing shows no backwards compatibility issues with porting base to rust 1.39.

**Comment by pjenvey** [comment]
Dockerfile updated in #328 and db_tests in #332
