### ISSUE TITLE
Firefox Preview doesn't sync with other FF browsers using a Spanner account

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#342]
Via Stefan from Bugzilla [1596378](https://bugzilla.mozilla.org/show_bug.cgi?id=1596378)

Devices:

    Nokia 6 (Android 7.1.1);
    Samsung Galaxy Note S8 (Android 9);

Build:

    Firefox Preview 2.3.0 (#13031728);

Prerequisites:
Login on multiple devices with the same Firefox account.

Steps to reproduce:

    Make sure that you are connected to the account in test;
    On both devices, spend some time to create some new browsing data;
    Sync first device than the second device;
    Pay attention to what data was synced between those two devices.

Expected results:
All of the new data created while browsing on those two devices should now be synced.

Actual results:
Fenix browser doesn't sync with the other types of browsers(FF for desktop, FF for iOS, FF for Android).

Notes:

    This issue is reproducible only with the Spanner accounts;
    The Fenix browser starts the sync and appears as synced on other devices on the manage account section.
    The Last sync data on the Firefox Preview browser it says an old data(ex. Last synced: Jan 1, 1970);
    This issue is not reproducible with FF for Android, FF for Desktop or FF for iOS.

**Comment by jrconlin** [comment]
I think I've identified the error in the logs at least:
```
I/sync15::client: Request "/1.5/###/info/configuration" has incoming x-last-modified ServerTimestamp(1573697264890)
I/sync15::client: Request "/1.5/###/info/collections" has incoming x-last-modified ServerTimestamp(1573697264890)
I/sync15::client: Request "/1.5/###/storage/meta/global" has incoming x-last-modified ServerTimestamp(1573684707540)
D/sync15::client: Got meta global with modified = 1573684707.54; last-modified = 1573684707.54
I/sync15::state: Have info/collections and meta/global. Computing new engine states
D/sync15::state: compute_engine_states: input EngineStateInput { local_declined: {"greasemonkey", "passwords"}, remote: Some(RemoteEngineState { info_collections: {"forms", "meta", "bookmarks", "prefs", "passwords", "crypto", "tabs", "history", "addons", "clients"}, declined: {"greasemonkey", "passwords"} }), user_changes: {} }
W/sync15::state: Remote state contains engines which are in both info/collections and meta/global's declined: {"passwords"}
D/sync15::state: compute_engine_states: output EngineStateOutput { declined: {"greasemonkey", "passwords"}, changes_needed: EngineChangesNeeded { local_resets: {}, remote_wipes: {} } }
D/sync15::state: SyncID for engine "passwords" was present, but shouldn't be
    SyncID for engine "addresses" was missing
    SyncID for engine "creditcards" was missing
I/sync15::state: Uploading corrected meta/global with timestamp ServerTimestamp(1573684707540)
I/sync15::client: Request "/1.5/###/storage/meta/global" was an error!
D/sync15::sync_multiple: Declined engines list after state machine set to: Some(["greasemonkey", "passwords"])
W/sync15::sync_multiple: sync failed: HTTP storage error: RequestFailed { route: "/1.5/###/storage/meta/global", status: 400 }, final status=ServiceError
    Backtrace: Some()
I/sync_manager::manager: Sync finished with status ServiceError
E/SyncWorker: Service error
```
I don't see this error when talking to the mysql logs. 
Currently chasing where in the code it's making that call. I suspect it's in the `android_components` rust lib.

**Comment by jrconlin** [comment]
Hitting an issue trying to compile a version of the rust-components so I can determine the root of the 400 error that's being generated above. While the libs compile, I'm unable to run `gradlew fenix-megazord:publishToMavenLocal` due to an error in nss compilation:

```
> Task :fenix-megazord:cargoBuildLinux-x86-64 FAILED
...
--- stderr
/home/jrconlin/src/mozilla/application-services/libs/desktop/linux-x86-64/nss/include/nss/prtypes.h:29:10: fatal error: 'stddef.h' file not found
```
I was able to resolve the problem by adding the following to my `local.properties` file:

```
# added per slack (the source machine for the build)
target.properties=linux-x86_64
# list of targets to build maven libraries for
# NOTE: there is a problem with linux-x86_64
rust.targets=arm,arm64,x86,x86_64
```

**Comment by rfk** [comment]
> I/sync15::client: Request "/1.5/###/storage/meta/global" was an error!

Are you able to see this failing request on the server side? I would expect this to be a `PUT /1.5/${syncid}/storage/meta/global` failing with a `400` error, and I would expect it to be sending an `X-If-Unmodified-Since` header in the request. Maybe some bad interaction trying to reflect this timestamp value back to the server?

**Comment by pjenvey** [comment]
AFAICT python syncstorage seems to also error out on such an empty put request. Although it produces code 6 (malformed json) instead of 8 (invalid wbo).

Strangely enough I don't see any special handling of these codes w/ a quick look at the app-services code base. So it's not clear why we're only seeing this on Spanner nodes.

**Comment by tublitzed** [comment]
@jrconlin let's keep this one open until we can get a release out to verify that the related PR fixes the issue.

**Comment by rfk** [comment]
FWIW I noticed that the latest version of Lockwise also seems to be failing in a similar way to the above, perhaps because they upgraded to a new version of the shared rust components.

**Comment by tublitzed** [comment]
I was able to verify just now using sync id `130387415` that Fenix bookmark sync is working. 

Hey, @rfk - we just did a release this AM with a fix for this one; are you still seeing the Lockwise issue?

**Comment by tublitzed** [comment]
(Going to keep this one in review until we get QA signoff here in the [related bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1596378))

**Comment by rfk** [comment]
Lockwise and Fenix sync are still failing for me, but they seem to be failing *differently*, which is progress I guess? I'll see if I can find out more useful info and either continue the conversation here, or open a fresh bug.
