### ISSUE TITLE
Utilize async/await

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#348]
Starting this off w/ documenting async/await topics of interest:

- actix-web's [Tracking issue for std::future migration](https://github.com/actix/actix-web/issues/1166)
- A basic example of async/await handlers (via wrapping them w/ `.compat()`): [try-async-await](https://github.com/zeljic/try-async-await)

**Comment by tublitzed** [comment]
https://github.com/mozilla-services/syncstorage-rs/issues/462

**Comment by tublitzed** [comment]
https://github.com/mozilla-services/syncstorage-rs/issues/439

**Comment by tublitzed** [comment]
We have one more issue to resolve the FE work (#439 filed to decide how to do it) but it's been de-prioritized now so marking the rest of this as complete.
