### ISSUE TITLE
Fenix sync fails to upload client record

### ISSUE THREAD

**Issue by rfk** [mozilla-services/syncstorage-rs#376]
Fenix (Nightly) sync is failing for me against the durable-sync backend. I see the following in logcat output:

```
12-13 10:11:45.274 10142 23768 I sync15::client: Request "/1.5/131779961/storage/crypto/keys" has incoming x-last-modified ServerTimestamp(1575599709030)
12-13 10:11:45.275 10142 23768 D sync15::sync_multiple: Declined engines list after state machine set to: Some(["addresses"])
12-13 10:11:45.276 10142 23768 I sync15::sync_multiple: Synchronizing clients engine
12-13 10:11:45.276 10142 23768 I sync15::clients::engine: Syncing collection clients
12-13 10:11:45.291  5458  7433 D ConnectivityService: filterNetworkStateForUid() uid: 10283, pid: 10142
12-13 10:11:45.291  5458  7433 D ConnectivityService: filterNetworkStateForUid() uid: 10283, pid: 10142, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
12-13 10:11:45.330  5458  5653 D WifiTrafficPoller: TrafficStats TxPkts=946766 RxPkts=1460160 TxBytes=147951549 RxBytes=1779986751 , Foreground uid=10283 pkgName=org.mozilla.fenix.nightly TxPackets=581582 RxPackets=851054 TxBytes=59351711 RxBytes=1159943631
12-13 10:11:45.547 10142 23768 I sync15::client: Request "/1.5/131779961/storage/clients" has incoming x-last-modified ServerTimestamp(1576184664970)
12-13 10:11:45.549 10142 23768 I sync15::request: Posting 1 records of 450 bytes
12-13 10:11:45.635   784   962 D BluetoothGatt: readRssi() - device: F2:21:8F:24:87:DB
12-13 10:11:45.888 10142 23768 I sync15::client: Request "/1.5/131779961/storage/clients" has incoming x-last-modified ServerTimestamp(1576192306270)
12-13 10:11:45.888 10142 23768 D sync15::request: Committed batch NoBatch
12-13 10:11:45.890 10142 23768 W sync15::sync_multiple: sync failed: Not all records were successfully uploaded, final status=OtherError
12-13 10:11:45.890 10142 23768 W sync15::sync_multiple: Backtrace: Some()
12-13 10:11:45.890 10142 23768 I sync_manager::manager: Sync finished with status OtherError
12-13 10:11:45.909 10142  1765 D sync_manager::manager: Not under backoff
12-13 10:11:45.910 10142  1765 I sync_manager::manager: No backoff in effect (or we decided to ignore it), starting sync
12-13 10:11:45.923 10142 23768 E SyncWorker: 'Other' error :(
```

The `Not all records were successfully uploaded` error indicates that when it tried to POST to the "clients" collection, the request returned `200 OK` but the response body had one or more items in the "failed" field.  In other words the quote-unquote successful request was actually a failure.

I'll see if I can add more logging to find out what the actual response body was.

**Comment by rfk** [comment]
The response body is:

```
{'failed': {'a7a382b7790dcaeac41e6c5303992b78': 'unknown field collection'}, 'modified': 1576273486.72, 'success': []}
```

So I guess this is a similar issue to https://github.com/mozilla-services/syncstorage-rs/pull/364, but for BSOs uploaded as part of a batch rather than individually.

**Comment by rfk** [comment]
I added some tests for this field in the functional test suite here: https://github.com/mozilla-services/server-syncstorage/pull/129

**Comment by mhammond** [comment]
Sorry that I'm late to the party here, and I hope I'm not missing something, but I think we discussed this with rnewman back in the day and there was a consensus we should basically kill the ability for individual records to fail in this way - it seems to defeat the batch concept (ie, a single bookmark record failing in a batch is a large problem). Should we open an issue to remove this capability (ie, remove the ability for individual records to fail and instead fail the entire post/batch)?

**Comment by pjenvey** [comment]
> Should we open an issue to remove this capability (ie, remove the ability for individual records to fail and instead fail the entire post/batch)?

Probably, but I've added this to the agenda for our next Sync Team meeting, let's discuss it first
