### ISSUE TITLE
Rewrite purge_ttl in Rust

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#385]
We're adding python to the Docker image right now specifically to run the [purge_ttl](https://github.com/mozilla-services/syncstorage-rs/blob/master/tools/spanner/purge_ttl.py) script. It'd be nice to be able to shed the weight of python support; let's rewrite this script in Rust, and then make sure we've coordinated with ops around adjusting their logic to use it.

**Comment by pjenvey** [comment]
It's a pretty small script, so I think a good start to this bug would be:

- Create a command line app in Rust that reads `SYNC_DATABASE_URL` from the environment
- Which then creates a Spanner client from, that then emits the two partitioned dml `DELETE` statements. This part would look similar to the code in the [spanner manager module](https://github.com/mozilla-services/syncstorage-rs/blob/2935846/src/db/spanner/manager.rs)

Once we have a the basic script running we can then add the extra features supported by the Python version:

- Emit timer metric to measure the duration of the calls (using the `cadence` metrics lib that syncstorage-rs already uses)
- Proper logging messages (`println!` would probably do to start with)
