### ISSUE TITLE
Implement KV trait for Tags

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#387]
KV's a trait that the `Tags` struct can implement. [slog-derive](https://github.com/slog-rs/derive) makes it easy.

Probably better to tackle that in a separate issue.

_Originally posted by @pjenvey in https://github.com/mozilla-services/syncstorage-rs/pull/372_

**Comment by undef1nd** [comment]
Hey @jrconlin , could you plz assign it to me? As agreed in email. Thanks.
