### ISSUE TITLE
Return `HttpResponse::build(status)` instead of `HttpResponse::OK` in case of error in middleware

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#393]
Around line 429 in middleware.rs

if status != StatusCode::OK {
             return Either::A(future::ok(
               sreq.into_response(
-                HttpResponse::Ok()
+                HttpResponse::build(status)

**Comment by pjenvey** [comment]
I'll note the `HttpResponse::Ok()` call here does in fact set the correct status, but `build` here would be cleaner. (This is now in middleware/precondition.rs line 177)

**Comment by fzzzy** [comment]
Yes, JR and I noticed this while pairing on something unrelated. It's not that important but `build` would just be a tiny bit cleaner.

**Comment by jrconlin** [comment]
Had a minute while doing some gc cleanup, so submitted the patch.
