### ISSUE TITLE
Upgrade to actix web 2.x

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#394]
It's probably worth making time to upgrade to 2.x before we get too far behind. Looks like 2.0 went live [9 days ago](https://github.com/mozilla-services/syncstorage-rs/issues/348), so not a huge rush, but filing so we've got it.

Can we do the actix upgrade as a standalone task without also converting everything to async/await? (we have a [separate task](https://github.com/mozilla-services/syncstorage-rs/issues/348) filed for async/await changes).

**Comment by fzzzy** [comment]
Yes, it looks like we can update to actix-web 2.0 and futures 0.3 without converting to async await. However, we have to do the entire futures 0.3 upgrade at once, including the database async parts. However the db is just one threadpool with a bunch of functions generated by macros, so it should be pretty easy to convert it to 0.3.

After that, we should be able to convert each actix handler to use async await one at a time. We should also be able to do the same for the db backend calls but I will have to do more work to investigate how much work that will be.

**Comment by tublitzed** [comment]
Awesome, thanks for digging into this @fzzzy! 

I'm assuming that the actix upgrade requires us to also upgrade futures, y? (Just making sure they can't be further spllit out).

**Comment by fzzzy** [comment]
Right, updating actix-web to 2 requires updating futures to 0.3, which means we have to update the database futures as well. But, we don't have to convert anything to async await at first, and can do it one function at a time.
