### ISSUE TITLE
Enforce the limits returned by /info/configuration

### ISSUE THREAD

**Issue by philbooth** [mozilla-services/syncstorage-rs#40]
In #39, the `/info/configuration` endpoint is implemented to return some static limits relating to payloads:

```rust
static KILOBYTE: u32 = 1024;
static MEGABYTE: u32 = KILOBYTE * KILOBYTE;
static DEFAULT_MAX_POST_BYTES: u32 = 2 * MEGABYTE;
static DEFAULT_MAX_POST_RECORDS: u32 = 100;
static DEFAULT_MAX_RECORD_PAYLOAD_BYTES: u32 = 2 * MEGABYTE;
static DEFAULT_MAX_REQUEST_BYTES: u32 = DEFAULT_MAX_POST_BYTES + 4 * KILOBYTE;
static DEFAULT_MAX_TOTAL_BYTES: u32 = 100 * DEFAULT_MAX_POST_BYTES;
static DEFAULT_MAX_TOTAL_RECORDS: u32 = 100 * DEFAULT_MAX_POST_RECORDS;
```

Most of these need to be enforced manually I guess, except for `DEFAULT_MAX_REQUEST_BYTES` which can be set wholesale at the web server level.

**Comment by thomcc** [comment]
Please be careful here WRT off by one errors. The clients expect MAX to be the highest valid value of these (see https://github.com/mozilla-services/server-syncstorage/pull/74).

If it helps at all, [the Desktop JS code](https://searchfox.org/mozilla-central/rev/881a3c5664ede5e08ee986d76433bc5c4b5680e6/services/sync/modules/record.js#821) is fairly well commented  in terms of explaining what the client expects from the limits.

**Comment by pjenvey** [comment]
#104 began enforcing all these limits except the 2 batch settings max_total_{bytes/records}

**Comment by pjenvey** [comment]
max_total_{bytes/records} are now checked as of #108.

Logged a somewhat related #114 for further enhancements from the go version.
