### ISSUE TITLE
Build the docs in CI and push them to the gh-pages branch?

### ISSUE THREAD

**Issue by philbooth** [mozilla-services/syncstorage-rs#42]
Over in `fxa-email-service` we have a Travis job that builds the docs and then pushes them to the `gh-pages` branch. This means we have automagically refreshing docs available here:

https://mozilla.github.io/fxa-email-service/fxa_email_service/

Are you guys interested in something similar for this repo?

**Comment by bbangert** [comment]
Looks good to me!

**Comment by pjenvey** [comment]
it could be the 2 == comparisons on that line this time? (use = instead.. if so, wow that's strict)

**Comment by philbooth** [comment]
All good now, closing.
