### ISSUE TITLE
Add minumum supported Rust version to cargo.toml

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#424]
Looks like it's [now supported](https://github.com/rust-lang/rfcs/pull/2495).

Probably makes sense to do this to avoid future issues with versions that are too old.

**Comment by pjenvey** [comment]
Reopening because I just noticed the RFC hasn't been implemented yet: https://github.com/rust-lang/rust/issues/65262

So #475 emits a harmless warning:

```
$ cargo build
warning: unused manifest key: package.rust
```

Let's revert it and just add the minimum version to the README for now

**Comment by tublitzed** [comment]
Ah shoot, thanks @pjenvey! Closing this now and will re-open if/when implemented.
