### ISSUE TITLE
Default slog log level to error

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#426]
In release mode, let's avoid logging all but the most critical (ERROR) log messages.

**Comment by pjenvey** [comment]
It may make sense to lower this to WARN or back to INFO later but there's a few WARN messages that we don't need to see currently

**Comment by jrconlin** [comment]
Honestly, I'd rather we keep the production level to "ERROR" only, and maybe drop to "WARN" if we want to diagnose unusual behavior. There should be no action we can take with anything less than ERROR. An alternate is that we only send ERROR to sentry and preserve things like WARN for the log archive.
