### ISSUE TITLE
Document the ACTIX_THREADPOOL env variable for use with mysql databases and change example config to set it to a large number

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#441]
We're now using the actix threadpool instead of tokio-threadpool in the actix-web 2 branch. Thus, there is a different environment variable, ACTIX_THREADPOOL, we need to set to set the size of the threadpool. It defaults to num_cores * 5. We should probably set it to 128 or some other large number.

**Comment by fzzzy** [comment]
We don't actually have to do this anymore, because we don't use the actix threadpool in the spanner client any more  🎉

**Comment by pjenvey** [comment]
We may or may not need to support this for mysql, reopening for a reminder to reevaluate this later.
