### ISSUE TITLE
Remove our custom async_test proc_macro (codegen crate) implementation

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#461]
Our `#[async_test]` proc_macro is based on [tokio-async-await-test](https://github.com/LucioFranco/tokio-async-await-test) but we implemented our own custom version to avoid build issues with the crate and its tokio deps that existed at the time.

That crate hasn't been updated in a while but there's likely alternatives (e.g. [futures-await-test](https://crates.io/crates/futures-await-test)) that we could switch to.

Our impl isn't a lot of code, so this is a low priority issue, but its existence requires the `codegen` sub crate which would be nice to get rid of.

**Comment by amrita72** [comment]
Hey @pjenvey! I'd like to work on this issue. From what I can make out; we need to
- remove `codegen` from [dev-deps] and from path
- remove `tokio` from [deps]
- add `futures-await-test` to [dev-deps] with the corresponding changes in `src/db/tests/{db,batch}.rs` files?

**Comment by pjenvey** [comment]
>     * remove `tokio` from [deps]

tokio may need to stay (but I'm not totally sure, try it :) )

> 
>     * add `futures-await-test` to [dev-deps] with the corresponding changes in `src/db/tests/{db,batch}.rs` files?

Yup, and hopefully its `#[async_test]` works similarly to ours from the codegen crate, so the changes here are just the couple imports of it.

**Comment by amrita72** [comment]
> tokio may need to stay (but I'm not totally sure, try it :) )

I tried compiling the project without `tokio`, everything seems to work just fine. All tests passed.
