### ISSUE TITLE
Clean up the non-dbtests usage of async code

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#462]
Now that actix-web 2 has landed and all the spanner database backend code is async await, we could continue to clean up the code a lot by modernizing the non-dbtests usage of handling async code.

**Comment by tublitzed** [comment]
hey @fzzzy could you add an estimate here?

**Comment by fzzzy** [comment]
Not yet, actually. I didn't want to estimate it until I actually looked at how much code is there. I think it's either a 3 or a 5, I'll look at it this afternoon and give it an estimate.

**Comment by fzzzy** [comment]
Basically, this means removing use of block( from src/db/spanner/models.rs.
