### ISSUE TITLE
GETs with a `limit` and no `sort` never advance `X-Weave-Next-Offset`

### ISSUE THREAD

**Issue by linacambridge** [mozilla-services/syncstorage-rs#468]
I've been able to reproduce this consistently in Nightly, from the Browser Console and the About Sync add-on, when I fetch all my bookmark records (that is, no `older`, `newer`, or `ids` query params; I haven't tested if those change anything).

I have just over 4k bookmarks, so the client tries to fetch them in batches. All my other collections sync successfully, since they have under 1k records.

Here's what I see in the logs:

```
1583458802175	Sync.Collection	DEBUG	GET success 200 https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/131779759/storage/bookmarks?full=1&limit=1000&offset=1575593490410%3A1
X-W-N-O = 1575593490410:1
X-L-M = 1583453382.92
X-W-R = 1000
[ ... ]
1583458802367	Sync.Collection	DEBUG	GET success 200 https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/131779759/storage/bookmarks?full=1&limit=1000&offset=1575593490410%3A1
X-W-N-O = 1575593490410:1
X-L-M = 1583453382.92
X-W-R = 1000
[ ... ]
1583458802544	Sync.Collection	DEBUG	GET success 200 https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/131779759/storage/bookmarks?full=1&limit=1000&offset=1575593490410%3A1
X-W-N-O = 1575593490410:1
X-L-M = 1583453382.92
X-W-R = 1000
[ ... ]
```

So it looks like `X-Last-Modified` stays the same (which is what we expect; otherwise, we'd see a 412), but `X-Weave-Next-Offset` never returns the next offset...so it gets stuck in an infinite loop fetching the first 1k records!

Please let me know if there's anything I can do to help debug! ❤️

**Comment by pjenvey** [comment]
The recently added pagination offset optimization has exposed a bug that I think causes this. See this comment in the Python:

https://github.com/mozilla-services/server-syncstorage/blob/master/syncstorage/storage/sql/queries_generic.py#L231

We're not always sorting by something, we don't `ORDER BY` anything when no sort order's specified. Python's instead treating no sort order as sort=newest (`ORDER BY modified DESC`). The optimization assumes ordering and won't work right without it.

(We inherited the behavior basically from go-syncstorage but I believe it lacked the offset optimization)

**Comment by linacambridge** [comment]
Ohhh, that explains why Desktop's Sync implementation never runs into this! 💡 It [always passes `sort=oldest`](https://searchfox.org/mozilla-central/rev/13b081a62d3f3e3e3120f95564529257b0bf451c/services/sync/modules/engines/bookmarks.js#844-846), even for a first sync, so the URL looks like `https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/131779759/storage/bookmarks?full=1&sort=oldest&limit=1000`.

But About Sync [doesn't](https://github.com/mhammond/aboutsync/blob/master/src/provider.jsx#L96-L97), and I didn't set it in the console, either.

**Comment by linacambridge** [comment]
So Desktop sets `sort=oldest` [for bookmarks](https://searchfox.org/mozilla-central/rev/13b081a62d3f3e3e3120f95564529257b0bf451c/services/sync/modules/engines/bookmarks.js#844-846) (and the [old bookmarks engine](https://searchfox.org/mozilla-central/rev/13b081a62d3f3e3e3120f95564529257b0bf451c/services/sync/modules/engines/bookmarks.js#363) sets `sort=index`), but [doesn't specify](https://searchfox.org/mozilla-central/rev/13b081a62d3f3e3e3120f95564529257b0bf451c/services/sync/modules/engines.js#1183-1187) `sort` for the other collections...so I think it might also run into this once a collection has over 1k records?
