### ISSUE TITLE
[mysql] Make the userid column a BIGINT

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#470]
The mysql schema defines the `userid` column in all tables as a regular 32 bit `INT`. This is incorrect: the userid is handed to syncstorage-rs via an auth token by the tokenserver, which [uses a 64 bit `BIGINT`](https://github.com/mozilla-services/tokenserver/blob/e25d636/tokenserver/assignment/sqlnode/schemas.py).

syncstorage-rs correctly parses the auth token into the `HawkIdentifier` struct, w/ userid (HawkIdentifier refers to it as `legacy_id`) [being 64 bits](https://github.com/mozilla-services/syncstorage-rs/blob/master/src/web/extractors.rs#L1060).

The [mysql db code](https://github.com/mozilla-services/syncstorage-rs/blob/f699085/src/db/mysql/models.rs) then casts `legacy_id` down to the a u32 (which truncates!) per the column type.

We need to:

- Create a new [diesel migration](https://github.com/mozilla-services/syncstorage-rs/tree/46c650a/migrations) to convert the column to a `BIGINT`
- Modify the [diesel schema](https://github.com/mozilla-services/syncstorage-rs/blob/317d960/src/db/mysql/schema.rs) accordingly
- Remove the truncating casts (though we still need to cast from `legacy_id`'s u64 type to `i64` which diesel expects for `BIGINT`s)

(This bug extracted from the original #74)

**Comment by Emmanuel-Melon** [comment]
Hi @pjenvey, this sounds like a good first issue. I'd love to give it a shot. I'll take a look at the codebase and then give you an update.

**Comment by undef1nd** [comment]
Hey @Emmanuel-Melon, are you working on this one? I'd like to give it a try 🙂

**Comment by Emmanuel-Melon** [comment]
Yes, I'm. I'm making a PR this week.
