### ISSUE TITLE
Pull Collections insert from DDL into own file

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#473]
Due to limitations in how spanner DDL operates, we should note that the `INSERT INTO collections...` statement out of `spanner-2019-10-01.ddl` should NOT be executed in series with the other lines of the DDL.

There should be some visual distinction as well as a comment stating that the `INSERT` command be run separately, but immediately after the other table creation steps.

**Comment by amrita72** [comment]
Hey @jrcoln. I'd like to work on this issue. As far as I can tell, we need to separate out [these lines](https://github.com/mozilla-services/syncstorage-rs/blob/44aa7cae5187b5e2d673dab2f7f84a8224445bb8/spanner-2019-10-01.ddl#L51-L64) into a separate file. Am I correct?

But, where and how are we actually using that `spanner-2019-10-01.ddl` file?

**Comment by jrconlin** [comment]
The `ddl` file is used by operations currently to create the database in spanner. It's not automated mostly because it's a one time thing that doesn't need to be automated. Mostly the file is cut and pasted into a web console. 

In this case, the file pretty much just needs to be rewritten, moving the `Insert` to the bottom with a comment section stating something like "Cut Here", after table creation, with a follow up that the insert should happen after table creation. 

It probably doesn't require coding, thus why it's a "Good First Bug" for folks.
