### ISSUE TITLE
Utilize Tags' slog::KV trait

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#503]
A Followup to #387:

Now that Tags implements the KV trait, let's convert all log statements to utilize it where appropriate. See the `Testing` section described in #493 for an example.

Note: let's be careful to ensure this change doesn't add excessive number of new tags to our log messages. I do believe this change will end up adding the `uri.method` tag to log messages, which is fine.

**Comment by undef1nd** [comment]
@pjenvey I’d like to work on this.

I guess I will need Sentry to make make sure that these changes don’t break anything. Am I right? Thanks.
