### ISSUE TITLE
Port get_bsos' pagination optimization

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#53]
A TODO item described here: https://github.com/mozilla-services/syncstorage-rs/blob/bea8032/src/db/mysql/models.rs#L242

**Comment by jrconlin** [comment]
Is this related to #205?

**Comment by pjenvey** [comment]
> Is this related to #205?

Nope, this is different.

It involves encoding some more information into the `next_offset` value passed to the client and an accompanying decoder of said value

**Comment by jrconlin** [comment]
Quick overview of work:
* Create new struct for `Offset` `{timestamp: Option<SyncTimestamp>, offset: i64}`
    * Include impl for From, Debug, etc.
* Convert `Paginated` to use `offset: Option<Offset>`
* Modify Mysql & Spanner to use new Offset heuristic 
* Add tests

**Comment by pjenvey** [comment]
A new struct may not be totally necessary if offset is just a String. The encode/decode methods can return the extracted types.

On the other hand the extractors could be responsible for producing this new struct and could even potentially validate the format.

This is an optional optimization, so the python version leaves impl. of it up to the db layer, for it to decide if it wants to support it
