### ISSUE TITLE
Convert get_collection* actix-web frontend calls to async await

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#540]
The actix-web frontend get_collection* calls:

  -  get_collections
      -  should be combined with finish_get_collection
  -  get_collection_counts
  -  get_collection_usage

Are in a Future style. They can now be converted over to use async/await syntax instead.

**Comment by Emmanuel-Melon** [comment]
@fzzzy This is very similar to #543, I can work on this.

**Comment by pjenvey** [comment]
All handlers have already been converted to async/await around the time we switched off the r2d2 Db Pool
