### ISSUE TITLE
Convert misc actix-web frontend calls to async await

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#541]
The actix-web frontend misc calls:

   - get_quota
   - delete_all
   - heartbeat
   - test_error

Are in a Future style. They can now be converted over to use async/await syntax instead.

**Comment by Emmanuel-Melon** [comment]
@fzzzy Hey there, I rewrote the listed functions in this manner
```
pub async fn get_quota(meta: MetaRequest) -> Result<HttpResponse, Error> {
    meta.metrics.incr("request.get_quota");
    let usage = meta.db.get_storage_usage(meta.user_id).await?;
    Ok(HttpResponse::Ok().json(vec![Some(usage as f64 / ONE_KB), None]))
}
```
Is everything on track here? Could you kindly assign me this issue so I could create a PR?
