### ISSUE TITLE
Convert actix-web middleware to async await

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#545]
In our Actix middleware `Service` implementations, we invoke `and_then()` on the `Future` returned by [`Service::call`](https://docs.rs/actix-service/1.0.6/actix_service/trait.Service.html#tymethod.call). Now that Rust supports async/await, this is no longer idiomatic. Instead, we should wrap the `call()` invocation in a `Box::pin(async move { ... })` block as we do in the extractors. This would allow us to use async/await.

**Comment by pjenvey** [comment]
#714 (`wrapfn`) might help in getting rid of the async (at least the transform bits), or at least may help in their refactoring.

**Comment by ethowitz** [comment]
[JIRA](https://mozilla-hub.atlassian.net/browse/CONSVC-1684)

**Comment by ethowitz** [comment]
I could be wrong about this, but since the middleware traits aren't defined with `#[async_trait]`, I don't think we can apply `#[async_trait]` to the middleware implementation, so I'm not sure if this is possible
