### ISSUE TITLE
Update instructions for running via Docker

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#546]
It looks like now that we've [vendored the mozilla-rust-sdk](https://github.com/mozilla-services/syncstorage-rs/pull/477) into the repo, we can adjust the relevant instructions in the [running via Docker](https://github.com/mozilla-services/syncstorage-rs/blob/master/README.md#running-via-docker) section of the README.

**Comment by Emmanuel-Melon** [comment]
Hi @tublitzed I would like to work on this
