### ISSUE TITLE
Emit db Pool state metrics

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#555]
There should be metrics emitted about our db Pool periodically. E.g. the number of connections in use and possibly the number of idle connections.

`r2d2::Pool` & `cadence::StatsdClient` are both Sync, so we should be able to run a background thread holding references to both, polling the Pool for its current state and emitting a metric every e.g. 15-30 seconds.

**Comment by tublitzed** [comment]
For context, this is related to the [recent issue](https://firefoxoperations.statuspage.io/incidents/fwx9x6099zl5) that cropped up on March 30th.

**Comment by pjenvey** [comment]
Reopening: we want these metrics to emit a hostname tag for distinguishing between nodes
