### ISSUE TITLE
Test against and add docs for working with the cloud spanner emulator, integrate with CI

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#566]
Looks like Google recently released a [cloud spanner emulator](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator) - Lets:

1. Test against this locally and then update our README with instructions on how specifically to use it with this service.
2. Get it hooked up to CI

**Comment by fzzzy** [comment]
@Emmanuel-Melon I think you are working on this, right?

**Comment by Emmanuel-Melon** [comment]
I wasn’t assigned to this issue but I could work on it if you’d like me to

**Comment by Emmanuel-Melon** [comment]
> @Emmanuel-Melon I think you are working on this, right?

It's running locally. Will let you know if I come across any issues.
