### ISSUE TITLE
Refactor the Spanner Client into a separate module/crate

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#588]
We've now built up a significant Spanner db client on top of the lower-level `gcp-grpc` (aka `googleapis-raw`) lib but it's currently intertwined into our `db.spanner` mod/`SpannerDb` implementation.

It should be split out into its own standalone module or crate (a sub crate of syncstorage-rs for now would be fine). The aim here is to begin fleshing out a higher level Spanner client that could be reused elsewhere, more immediately in e.g. our `purge_ttl` tool, or our `migration_rs` crate (if it's still needed) and in the future potentially outside of our codebase.

**Comment by fzzzy** [comment]
This is pretty much working:

https://github.com/fzzzy/spanner-client-rs

Needs tests and some more refactoring.

**Comment by fzzzy** [comment]
Initial pr is up:

https://github.com/mozilla-services/spanner-client-rs/pull/1
