### ISSUE TITLE
Update README per vendored mozilla-rust-sdk

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#598]
The README still mentions the need for the private [mozilla-rust-sdk](https://github.com/mozilla-services/mozilla-rust-sdk) repo, which is no longer the case since it was [vendored into this repo last month](https://github.com/mozilla-services/syncstorage-rs/pull/477).

**Comment by tublitzed** [comment]
Closing. This was done [here](https://github.com/mozilla-services/syncstorage-rs/commit/eb5fa003d183b81b146c12afd498e8bf3555f334#diff-04c6e90faac2675aa89e2176d2eec7d8)
