### ISSUE TITLE
Investigate rise in 5xx errors

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#625]
Erik reported a spike in 5xx errors [here](https://earthangel-b40313e5.influxcloud.net/d/5kIPrfbWj/sync-rs-prod?orgId=1&from=now-30d&to=now&fullscreen&panelId=41&refresh=1m) - let's take a look and see what we can do to fix.

**Comment by tublitzed** [comment]
Probably makes sense to wait on a release including the sentry improvements here: https://github.com/mozilla-services/syncstorage-rs/pull/604

**Comment by pjenvey** [comment]
At least one major contributing factor to the 5xx rise is #619: we're producing more `6-ALREADY_EXISTS Row [....] in table bsos already exists, status: 500 }` errors.

These have increased since around the time purge_ttl has been offline (I can't point to an exact rate due to to them being masked #613, but it's been evident over time).

These seem to be the most common errors showing up in error logs (as a notable observation until we fix #504)

**Comment by erkolson** [comment]
0.3.4 was deployed to production earlier today.  It does not appear to have had a significant impact on the 5xx count, however, the 6-day trend shows that the number has decreased dramatically as we get closer to 0 expired rows in the bsos table:
<img width="1629" alt="Screen Shot 2020-05-18 at 1 47 13 PM" src="https://user-images.githubusercontent.com/9535472/82243940-67e6eb00-990e-11ea-8128-198e5e2654ba.png">

**Comment by tublitzed** [comment]
Going to keep this one open to keep digging into why the error rate is higher than python sync.

**Comment by pjenvey** [comment]
per @Micheletto "~half our 5xx errors in prod are 502s because of: backend_connection_closed_before_data_sent_to_client" -- and "There's probably a timeout we could set that would move these into the 4xx class."

**Comment by pjenvey** [comment]
GCP case tracking this here: https://console.cloud.google.com/support/cases/detail/23615498?organizationId=442341870013

**Comment by pjenvey** [comment]
#821 is the main source of our 503s currently (when pods are killed due to OOMs we get a temporary large spike of 503s). Other known issues causing 503s are #861 and #882.

Closing out since these are all logged separately.

**Comment by pjenvey** [comment]
and I'll note large number of 502s mentioned earlier were resolved by https://github.com/mozilla-services/cloudops-infra/pull/2699 (bumping nginx's proxy_read_timeout and client_body_timeout)
