### ISSUE TITLE
[mysql] Re-enable offset optimization

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#645]
We implemented #53 (+ #469 related fix) but disabled it in #559. It should be re-enabled on the mysql backend without impacting Spanner: we probably don't want it enabled on Spanner at all at this point, so the extractor portion of this optimization needs to accommodate that.

**Comment by fzzzy** [comment]
To disable the optimization on spanner, we can make the offset an Option instead of just an integer as it is now. None means don't use the optimization, Some(5) means use the optimization with offset 5.

**Comment by jrconlin** [comment]
Going to WONTFIX this bug. See https://github.com/mozilla-services/syncstorage-rs/pull/724#issuecomment-659527141 for details.
