### ISSUE TITLE
Sentry cleanup

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#682]
We have a number of [issues in Sentry](https://sentry.prod.mozaws.net/operations/syncstorage-prod/) that it'd be worth combing through and cleaning up. Filing this to track:

* consolidating/merging identical issues
* ^can we automate these kinds of merges for future?
* preventing sending errors that aren't actually worth reporting to sentry (or flagging them with something we can easily filter)
* filing issues for the sentry problems that we suspect are actual bugs

**Comment by jrconlin** [comment]
Recorded #738, #739, #740, #734 

Set sentry to ignore future: 
* "HAWK authentication error" errors
* "Input BSO has duplicate ID" & "ALREADY_EXISTS" errors
