### ISSUE TITLE
Remove old DB middleware

### ISSUE THREAD

**Issue by Mcat12** [mozilla-services/syncstorage-rs#693]
After the bb8 refactor (#692), the DB middleware (`src/web/middleware/db.rs`) is unused. It should be deleted.

**Comment by jrconlin** [comment]
![image](https://user-images.githubusercontent.com/35755/86051193-e359b300-ba09-11ea-9f1d-318024ea3a92.png)

**Comment by pjenvey** [comment]
DbMiddleware is the last user of `queue_report`, so we should kill it along with the middleware. Basically reverting most if not all of #604 which is not a small chunk of code.
