### ISSUE TITLE
Remove unnecssary `SyncServerRequest` implementation

### ISSUE THREAD

**Issue by AzureMarker** [mozilla-services/syncstorage-rs#694]
`SyncServerRequest` is implemented for both `ServiceRequest` and `HttpRequest` in almost exactly the same way. This occurred during the bb8 refactor (#692). However, `get_hawk_id()` is no longer called by a `ServiceRequest` anywhere in the repository (after a refactor relating to the DB middleware), so we can remove the impl for `ServiceRequest`.

**Comment by jrconlin** [comment]
TODO: This bug needs a lot more context and description before we can make it a "good first bug".

**Comment by ethowitz** [comment]
[JIRA](https://mozilla-hub.atlassian.net/browse/CONSVC-1693)
