### ISSUE TITLE
Avoid splitting `ServiceRequest` into parts to access the DB pool

### ISSUE THREAD

**Issue by Mcat12** [mozilla-services/syncstorage-rs#695]
Due to the bb8 refactor (#692), `PreConditionCheckMiddleware` splits the `ServiceRequest` into `HttpRequest` and the payload in order to use the DB pool extractor (`extrude_db_pool`):
https://github.com/mozilla-services/syncstorage-rs/blob/3a5fddb54b7641f7bb93d340d0728c64b70cf3bb/src/web/middleware/precondition.rs#L125-L129

The parts are then recombined to get the `ServiceRequest` back. The recombining code will fail if there is more than one reference to the request (i.e. if it has been cloned), as that is an invariant of `ServiceRequest`. This is a liability, so we should try to refactor that code to access the DB pool without splitting the service request into parts.

**Comment by pjenvey** [comment]
The latest switch-to-bb8 updates likely negate this (killing the PreconditionCheck middleware)

**Comment by fzzzy** [comment]
bb8 is merged and this is killed now.
