### ISSUE TITLE
Simplify DbPool async_trait usage and remove unnecessary generics after bb8 refactor

### ISSUE THREAD

**Issue by AzureMarker** [mozilla-services/syncstorage-rs#697]
Two minor refactors related to the DB pool code after the bb8 refactor (#692):

1. A generic was added to `SpannerConnectionManager`. It is not used and should be removed.
2. When the `DbPool` trait was made async, it did not require the returned futures to be `Send`:
    https://github.com/mozilla-services/syncstorage-rs/blob/3a5fddb54b7641f7bb93d340d0728c64b70cf3bb/src/db/mod.rs#L66
    We can tighten this bound to require `Send` by changing the annotation to `#[async_trait]`. This is the default for `async_trait`, so this change will simplify the code.

**Comment by AzureMarker** [comment]
> Since that bug was filed, there was some refactoring that went on with DbPool. The `Send` trait is still required because `DbPool` is exchanged between threads by `HttpServer`. I don't believe that it's necessary to remove the `Send` trait from `Box<DbPool>`.

https://github.com/mozilla-services/syncstorage-rs/pull/1134#issuecomment-893879805

@jrconlin This bug doesn't say to remove the `Send` bound, but to require it for `DbPool` implementations (by removing the `?Send`, which allows non-`Send` implementations). Therefore, this issue should be reopened since it's not fully fixed (or split it in two).

**Comment by jrconlin** [comment]
Yeah, you're right. @tiftran Let's file a new ticket to remove the `(?Send)` from `async_trait`.
