### ISSUE TITLE
Add back tuple-extractor pattern to extractors

### ISSUE THREAD

**Issue by AzureMarker** [mozilla-services/syncstorage-rs#698]
Due to the bb8 refactor (#692), some extractors which used the generic tuple extractor were changed to extract each item individually (due to a lifetime issue):
```rust
// From...
let (user_id, collection, query, mut bsos) =
    <(
        HawkIdentifier,
        CollectionParam,
        BsoQueryParams,
        BsoBodies,
    )>::from_request(&req, &mut payload)
    .await?;
// ...to...
let user_id = HawkIdentifier::from_request(&req, &mut payload).await?;
let collection = CollectionParam::from_request(&req, &mut payload).await?;
let query = BsoQueryParams::from_request(&req, &mut payload).await?;
let mut bsos = BsoBodies::from_request(&req, &mut payload).await?;
```

The issue which prompted this change has been fixed, so we can revert back to the tuple-extractor pattern. However, it's not clear which method is more efficient. If the tuple-extractor version is better, we should revert back to that pattern.

**Comment by fzzzy** [comment]
There's only one await in the tuple extractor version, so it seems like there'll be a lot less stack munging in that version.

**Comment by Emmanuel-Melon** [comment]
@fzzzy Hey there! I'm back to contributing and I'd like to start working on this to brush up.

**Comment by jrconlin** [comment]
Hey @Emmanuel-Melon, @fzzzy is out this week on PTO. Feel free to assign this to yourself and dig in if you like.
