### ISSUE TITLE
Avoid BatchExpiry index hotspots

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#706]
We're getting reports of latency spikes that are tied to the BatchExpiry key. Google has told us that keys that are timestamps can cause hot-spotting and should be avoided.

Before we just kill the secondary index BatchExpiry key, we should test code performance by having the calls in `batch.rs` do filtering of the returned batches themselves instead of having spanner filter the results for us. The `validate` call was causing the most trouble and should definitely be fixed.

**Comment by pjenvey** [comment]
AFAICT BatchExpiry seems to solely be utilized by the purge script. Even for the batch validate `SELECT` statement: it does a table scan and doesn't hit the index.

We should definitely remove the current INDEX to avoid the hotspots, but the purge script would still benefit from some kind of expiry index. Interleaving it with user_collections (just like BsoExpiry) might be the best option.

**Comment by pjenvey** [comment]
We've killed the INDEX with no replacement. An interleaved version of this index wouldn't provide much benefit: we found the batches table generally doesn't have much in it (=~ 2900 rows). The purge job without the INDEX so far seems to take about the same amount of time as with the INDEX (6-7 minutes).
