### ISSUE TITLE
Decide on a new min_idle for the bb8 database pool

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#712]
r2d2 created database connections ahead of time up to the max size. bb8 only creates min_idle connections up front. We should experimentally determine what value to use. (And also maybe change max_size by experimenting?)

**Comment by pjenvey** [comment]
#729 added this as a setting (e.g. `SYNC_DATABASE_POOL_MIN_IDLE`). Leaving open for now as we may want to try different values

**Comment by pjenvey** [comment]
Google recommends the equivalent of no value for MIN_POOL_IDLE as creating conns (sessions) in batches is more efficient than on demand.

We're a little different than most Spanner clients in that we don't multiplex multiple channels over a grpc connection (yet) -- but I don't think this affects their recommendation.

So there's nothing left to do here: the default of None is fine.
