### ISSUE TITLE
[purge-ttl] Consider using `REGEXP_CONTAINS()` for fxa_uid group matching

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#735]
see https://cloud.google.com/spanner/docs/functions-and-operators#regexp_contains

right now we do simple SQL `like 'a%'` for grouping. Unfortunately, spanner doesn't support ranges so `like '[0-9]%` won't work. They do provide `REGEXP_CONTAINS(column, pattern)` which would let us build ranges.

**Comment by pjenvey** [comment]
Confirmed the `BatchExpiry` index will still be used with it:

<img width="1032" alt="Screen Shot 2020-08-10 at 2 34 32 PM" src="https://user-images.githubusercontent.com/14639/89833855-a4457400-db16-11ea-963f-ca3f3ac423e8.png">
