### ISSUE TITLE
Only report 5** errors to sentry

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#738]
https://sentry.prod.mozaws.net/operations/syncstorage-prod/issues/9035922/
https://sentry.prod.mozaws.net/operations/syncstorage-prod/issues/9035959/
https://sentry.prod.mozaws.net/operations/syncstorage-prod/issues/9036224/

For 401 or similar errors, consider using metrics that report the UA, version and maybe genericized endpoint (e.g. 
`/1.5/##/info/collections`

**Comment by pjenvey** [comment]
Closing out (superseding this by https://mozilla-hub.atlassian.net/browse/SYNC-3413)
