### ISSUE TITLE
Record RESOURCE_EXHAUSTED as a metric

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#741]
https://sentry.prod.mozaws.net/operations/syncstorage-prod/issues/8179009/?referrer=github_plugin

This is not a directly actionable error and should be recorded as a metric.

**Comment by pjenvey** [comment]
#616 covers this, I would say it is (hopefully) actionable. We have to look into it and see if we can avoid it.

**Comment by jrconlin** [comment]
True, but I believe the error could still be covered as a metric rather than going into sentry. We're going to probably continue to get a baseline of these and I rather they be measured accordingly rather than as individual events.

**Comment by pjenvey** [comment]
Closing per https://github.com/mozilla-services/syncstorage-rs/issues/616#issuecomment-678339888
