### ISSUE TITLE
Set and respect storage quota per user collection.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#746]
We need to set a quota server side (2GB) and return a error to clients that will cause them to fail to sync (and log details) in this instance. This is to support spanner limitations.

Quota should be configurable server side to avoid need to do a train release to make changes there. Ideally it's some config var that will also prevent us from needing to do a server side release as well.

We also need to add tracking for this on the server side so we can see how many users this is affecting.

### Related docs:
* [Sync Quota Detection](https://docs.google.com/document/d/1R3I06Os0QJdoDY1VnO-Pr0rBlZfVLh1K7mVQS0Ccdqs/edit#heading=h.h2lsi0fznyih)
* [Sync users > 2GB mitigation](https://docs.google.com/document/d/1-vE423-65KlnAWWDH5yqhVE-Tr0eV-iVh_qrsJmAyRE/edit)
* [Sync Tombstone Learnings](https://docs.google.com/document/d/1MIl6aZXt4wMy6Tf6ZLSRShcPrk9v0DOgt6c1IHrs1U4/edit#)

**Comment by jrconlin** [comment]
See [internal doc](https://docs.google.com/document/d/1-vE423-65KlnAWWDH5yqhVE-Tr0eV-iVh_qrsJmAyRE/edit)

**Comment by rfk** [comment]
FWIW the server protocol docs already reserve [400 Bad Request with error code 14](https://moz-services-docs.readthedocs.io/en/latest/storage/apis-1.5.html#http-status-codes) for "user has exeeded their quota", and there is even a [special failure status](https://searchfox.org/mozilla-central/rev/c6676771df58c6e0098574bc6b11517acbf264cf/services/sync/modules/policies.js#1013) for this in the desktop client code. I don't think this special failure status provides an satisfying UX or anything like that, but if nothing else it should help the failure show up in an intelligible way in the sync logs.

**Comment by jrconlin** [comment]
As noted in the bug: We will definitely use these codes, since we're not doing so currently. I'd like to push for better UX as well and suggest the client be mindful if storage reaches some threshold less than the absolute limit. I suppose the server should probably broadcast what that absolute limit may be since it may vary per user or service.

**Comment by tublitzed** [comment]
@jrconlin to confirm that the client does indeed behave as expected re: the existing "exceeded quota" error code, would it be possible to get us to a point where we could confirm that against staging next week via some forced response mechanism? My thinking is that if for some reason the client (let's assume release versions of all) does _not_ behave as expected, we want to know that ASAP given the release train schedule. Even if we hack together something that forces this response on a normal sync for say, a specific account or something like that, I think that might be enough to confirm this. (Then we do the actual implementation work in future weeks/etc).

**Comment by jrconlin** [comment]
I'll see what I can come up with. It might be possible to have the server return something based on a passed header.

**Comment by tublitzed** [comment]
Thanks JR. I'll track testing results [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1655531) whenever you're ready.

**Comment by jrconlin** [comment]
Per Rachel's requirements:

```
No random versions. Latest of all. But when you get back, what about:

    Hardcode a few test FxA account ids into the sync response. (ie, my accounts, or QA/etc)
    When those tests ids come through, hardcode a forced response of what we want.
    Also send this error to sentry.
    Deploy to staging only (then we revert changes doesn’t need to go to prod)
    I test with those fxa accounts against staging.
    We confirm we see errors in Sentry.
```

**Comment by tublitzed** [comment]
@jrconlin to be clear, that's one possible approach here, not requirements :)

What we need to do here is:

1. Mimic exact client behaviour that we know will trigger this. Ie, try to sync > some threshold, see a returned quota error (or that it's triggered in some way). I'd suggest we go with less than 2GB of data to make testing easier, so if you want to hardcode it to something small, that'd be great.
2. For desktop - looking at the sync logs should be enough to verify. Latest version of desktop is fine.
3. For mobile (iOS, Fenix, Fennec) - since we don't have sync logs easily accessible there without running locally I would suggest we send a server side error to sentry so we can confirm this that way. If you have an easier way to confirm, that's fine too.

**Comment by tublitzed** [comment]
Re-opening as what was implemented was the ability to validate client behaviour, not the actual feature. @jrconlin did you want to track that as a separate ticket, or are we good to just keep this one around for it?

**Comment by jrconlin** [comment]
Let's keep this ticket open for now.

**Comment by jrconlin** [comment]
Related issues:
#789 
#790 
#791

**Comment by jrconlin** [comment]
closed as part of https://github.com/mozilla-services/syncstorage-rs/pull/806
