### ISSUE TITLE
Provide executables/packages for common platforms

### ISSUE THREAD

**Issue by n-peugnet** [mozilla-services/syncstorage-rs#753]
Hi,
I don't know if this rewrite of the syncstorage server is ready for production. But if it is, will you provide executables for common platforms (especially `x86_64-unknown-linux-gnu`) or even better, packages for common Linux distributions (especially Debian) ?

I would really prefer to run this rust version of the server instead of the python2 one.

Thanks.

**Comment by pjenvey** [comment]
We won't distribute individual executables but we do provide a docker image -- with the caveat that it's currently for our own purposes. See #304 for more information and feel free to add further discussion there (as I'm closing this ticket out :grin:).

**Comment by pjenvey** [comment]
and I wouldn't say it's ready for production for self hosters yet (w/ the mysql backend) as we're currently focusing on the Spanner backend.
