### ISSUE TITLE
`make test` fails on Fedora32 while linking with `cc`

### ISSUE THREAD

**Issue by lyuyuan** [mozilla-services/syncstorage-rs#755]
**Build Error:**

SYNC_DATABASE_URL='mysql://ylyu:xxxxxx@localhost/syncstorage_rs' RUST_TEST_THREADS=1 cargo test
   Compiling syncstorage v0.4.2 (/home/ylyu/xxxxxx/syncstorage-rs)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L"
...
...
...
  = note: /usr/bin/ld: /home/ylyu/xxxxxx/syncstorage-rs/target/debug/deps/libopenssl-82ea33565d1eae7c.rlib(openssl-82ea33565d1eae7c.openssl.c9volg5w-cgu.0.rcgu.o): undefined reference to symbol 'OPENSSL_cipher_name@@OPENSSL_1_1_1'
          /usr/bin/ld: /usr/lib64/libssl.so.1.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
error: aborting due to previous error
error: could not compile `syncstorage`.
To learn more, run the command again with --verbose.
make: *** [Makefile:35: test] Error 101

**Full error log can be found here on Mozilla Community Pastebin: http://paste.mozilla.org/PALCxW0v**

**Comment by jrconlin** [comment]
This looks like you might be missing the `libssl` package on your system, or you may have a version that is either more or less recent than libssl 1.1.1. Several component crates (like `curl`, `grpcio`, etc.) make calls out to libssl. Making things a bit more complicated, `grpcio` brings in it's own SSL/TLS library called `boringssl`. This can sometimes cause conflicts with libssl, and many of the other crates don't support `boringssl`.

Please make sure you have `libssl-1.1.1` installed, and if things compile, but you then get a SEGFAULT during app startup, you may want to include [something like this](https://github.com/mozilla-services/syncstorage-rs/pull/754/files#diff-80398c5faae3c069e4e6aa2ed11b28c0) in your Cargo.toml file. You may need to change the target to match your system. 

One last thing to note. OpenSSL is both heavily used and very finicky. If you already have OpenSSL installed, you *may* want to run syncstorage-rs inside of a virtual machine or Docker instance just to prevent possible problems with having two OpenSSL libraries installed on your system.

**Comment by lyuyuan** [comment]
> Please make sure you have `libssl-1.1.1`
Thanks for replying. I will remove the most recent version I installed and try libssl-1.1.1.

**Comment by lyuyuan** [comment]
> OpenSSL is both heavily used and very finicky.

It turns out this was the root cause of my problem. I removed existing OpenSSL libraries, and build finally succeeded. Thanks

**Comment by JadeVane** [comment]
Same here:

```
RUST_LOG=debug RUST_BACKTRACE=full cargo run --features tokenserver_test_mode -- --config config/local.toml
   Compiling syncstorage v0.10.2 (/var/www/syncstorage-rs)
error: linking with `cc` failed: exit status: 1
  |
  = note: ...
  = note: /usr/bin/ld: /var/www/syncstorage-rs/target/debug/deps/libopenssl-08e88a2d070c9cad.rlib(openssl-08e88a2d070c9cad.openssl.787bc7d6-cgu.1.rcgu.o): undefined reference to symbol 'OPENSSL_cipher_name@@OPENSSL_1_1_1'
          /usr/bin/ld: //lib/x86_64-linux-gnu/libssl.so.1.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `syncstorage` due to previous error
make: *** [Makefile:39: run] Error 101
```

`libssl-1.1.1` had been installed, what can i do now
