### ISSUE TITLE
Sub-section environment configuration options not being read properly

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#762]
From limited local testing:

~1) `Config` wants the prefix to match case, PREFIX should be UPPERCASE~
2) The default separator is ".", which can cause some shells to improperly recognize the env var.

(e.g. `SYNC_LIMITS.DEBUG_CLIENT=2 cargo run`) produces a shell error `SYNC_LIMITS.DEBUG_CLIENT=2: command not found`

Suggest that double underscore be used as the separator value.

**Comment by pjenvey** [comment]
Some previous discussion of this here: https://github.com/mozilla-services/syncstorage-rs/issues/320#issuecomment-550553615

**Comment by jrconlin** [comment]
Oh, yeah. Forgot about that one. Thanks! I'll amend the PR to reference that issue too.
