### ISSUE TITLE
"Invalid Accept" should be more descriptive

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#772]
https://sentry.prod.mozaws.net/operations/syncstorage-stage/issues/9334203/?environment=release&referrer=alert_email

This error should be a bit more descriptive so that future folk understand what it means or at least how to best find it.

e.g. "Invalid value specified for 'Accept` header in Collection request" or something.

(May want to be a bit more clear with other errors as well)

**Comment by fzzzy** [comment]
It appears this was already closed by https://github.com/mozilla-services/syncstorage-rs/pull/784

However, the syntax "Closes #xyz, #abc" is not a syntax that works to automatically close #abc.
