### ISSUE TITLE
Convert some validation/processing errors to metrics

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#808]
Seeing an increase in the number of validation errors like https://mail.google.com/mail/u/0/#inbox/FMfcgxwJXfkFBVcwmnBcPSHwHlzzwHJF.

These can be turned into metrics so we don't flood ourselves.

**Comment by fzzzy** [comment]
That's a link that I think only you can see. Can you paste the actual sentry link?

**Comment by jrconlin** [comment]
d'oh, dupe of #795  
Example error: https://sentry.prod.mozaws.net/operations/syncstorage-prod/issues/9482184/?environment=release&referrer=alert_email
