### ISSUE TITLE
Remove hard-coded values from tokenserver route

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#898]
The initial tokenserver spike hardcoded some values. Let's move some of them to settings.

**Comment by fzzzy** [comment]
Key material needs to be moved into an environment variable. Use the same name as the existing python tokenserver uses.

Default expires value needs to be moved into an env var.

**Comment by tublitzed** [comment]
Looks like we have one more hardcoded value [here](https://github.com/mozilla-services/syncstorage-rs/blob/master/src/web/tokenserver.rs#L243) that we should probably address here. Re-opening.

**Comment by jrconlin** [comment]
[Jira ticket](https://jira.mozilla.com/browse/CONSVC-155)
