### ISSUE TITLE
Port integration tests to python3

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#911]
The integration tests are still python2 and are becoming more difficult to run as dependencies slowly drop support for python2. The way the circle config runs the tests could also be far more efficient if we ran the tests under python3 in the same docker image without using docker compose.

**Comment by pjenvey** [comment]
Another TODO with moving these tests: Ops deployment pipeline runs the e2e tests on a live Spanner instance via the server-syncstorage docker.

We'll need to work with them to replace it with the Python 3 version.

**Comment by fzzzy** [comment]
I'd rather just put the old e2e docker instance back for now, since we're tight on time.

**Comment by pjenvey** [comment]
IMO this effort is more like an 8 score but feel free to switch it back to 5 if anyone disagrees.
