### ISSUE TITLE
Ensure that the hashed device ID and hashed FxA UID are identical to those in the old Tokenserver

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#925]
Currently, we generate a reasonable hash in both places, but they are not absolutely identical. Since they are used for metrics affinity, we'd see metrics become disconnected from previous metrics that user logged unless the hashes are identical.

They may already be, but timestamps in the to-be-hashed value may be making it hard to tell if the hash is correct or not at the moment.

**Comment by fzzzy** [comment]
We'll want to test this on stage to compare live python and rust tokenservers, so we'll do this work in Q1.

**Comment by jrconlin** [comment]
[Jira ticket](https://jira.mozilla.com/browse/CONSVC-156)

**Comment by ethowitz** [comment]
This will be verified by an integration test
