### ISSUE TITLE
Investigate 0.8.2 node hitting max db connections

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#945]
Following the 0.8.2 deploy yesterday a node became "stuck" with the max (30) number of db connections.

<img width="289" alt="Screen Shot 2020-12-03 at 3 34 30 PM" src="https://user-images.githubusercontent.com/14639/101101285-16860c80-357d-11eb-91c6-be17157b3a04.png">

The node continued serving requests until ops manually killed it, but its response times were incredibly slow (e.g. mostly in double digits seconds). Its affect on the overall 95th percentile:

<img width="593" alt="Screen Shot 2020-12-03 at 3 35 05 PM" src="https://user-images.githubusercontent.com/14639/101101445-75e41c80-357d-11eb-8cc1-7c9da5281418.png">

(and it triggered the nginix GET dashboard alarm).

**Comment by pjenvey** [comment]
Documenting more detail about these incidents [here](https://docs.google.com/document/d/1DOFcJ64HgSBEnCdUp4UyrDspNDqVA6D_7PIVYt5fLXk/edit#)

**Comment by tublitzed** [comment]
We haven't hit this in prod since https://github.com/mozilla-services/syncstorage-rs/pull/985 rolled out - closing.
