### ISSUE TITLE
10K Quota not being enforced in STAGING

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#949]
When setting 0.8.2 to have a QUOTA of 10,000K, QA is able to send a larger block of data. This may be due to quota enforcement happening after  the first block is loaded (due to issues with how the block content can be processed). 

Need to ensure that blocks are handled properly for QA meaning:
1) Ensuring that quotas are properly applied
2) determining the optimum block size for the reduced quota (possibly asserting that block size is smaller than quota?)
3) noting steps for Ops to configure a QA testing setup.

**Comment by jrconlin** [comment]
I've discovered that because we're using Mutations, spanner [does not "Read your writes"](https://cloud.google.com/spanner/docs/dml-versus-mutations), therefore, the quota resolution may take one or two additional transactions to eventually resolve itself. Normally, batches are a small fraction of the total quota, so while this may lead to an overage, eventually folks that have exceeded the quota would be prevented from using additional space. (Our quota is currently set at half of what Spanner allows, partly because of that).

For QA testing, some additional env vars may be useful on stage:

```bash
SYNC_ENABLE_QUOTA=true 
SYNC_ENFORCE_QUOTA=true 
SYNC_LIMITS__MAX_QUOTA_LIMIT=10000 
SYNC_LIMITS__MAX_POST_BYTES=10000 
SYNC_LIMITS__MAX_RECORD_PAYLOAD_BYTES=10000 
```
This sets the quota, post and payload max to 10K.

**Comment by vasilicatamas** [comment]
@jrconlin Where should these env vars be created? Because I created them in about:config but with no effect - the sync quota was not limited to 10K.

**Comment by tublitzed** [comment]
@vasilicatamas - they are configured in GCP - we'll need to set this up on our end for them to be applied correctly.

**Comment by jrconlin** [comment]
Correct, these values need to be set on the server that is running on stage. 

The PR that contains a slight work around is still pending review. If we use the existing version on Stage, I expect that once the server has been restarted using these values, that Quota detection will require a few loads beyond the 10K limit. This is because the server code only calculates the quota from previously entered data, not from the currently loaded data, so there's some "lag" during the load process.

(Note: This is not a significant concern even in production, because the normal POST bytes and Payload sizes are a small fraction of the overall Quota limit, and some "overage" is to be expected. Because we're using a greatly reduced Quota for testing purposes, some anomalous behavior is to be expected. It may be best to consider the Quota limiting to be more like an "eventually consistent" system rather than a hard limit.)
