### ISSUE TITLE
Add `deadman` switch if a connection pool stays exhausted for a period of time

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#984]
The nodes that are killed generally have zero available connections over a long period. 
(e.g. this snapshot from Active Connections: 
![image](https://user-images.githubusercontent.com/35755/105928078-20b30d00-5ffa-11eb-8b01-fa3577d15066.png))

A simple deadman switch would kill a server once the connection pool stays exhausted past a certain period of time.

**Comment by pjenvey** [comment]
Closed in #985 (not so much a switch but enable the cluster to "switch" via `__lbheartbeat__` feedback)
